//
// ApiKeyUsageDetail.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ApiKeyUsageDetail: Sendable, Codable, Hashable {

    public var apiKeyId: String?
    public var currentPeriod: CaptureUsageCounts
    public var keyPrefix: String?
    public var name: String
    public var totals: CaptureUsageCounts

    public init(apiKeyId: String? = nil, currentPeriod: CaptureUsageCounts, keyPrefix: String? = nil, name: String, totals: CaptureUsageCounts) {
        self.apiKeyId = apiKeyId
        self.currentPeriod = currentPeriod
        self.keyPrefix = keyPrefix
        self.name = name
        self.totals = totals
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case apiKeyId
        case currentPeriod
        case keyPrefix
        case name
        case totals
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(apiKeyId, forKey: .apiKeyId)
        try container.encode(currentPeriod, forKey: .currentPeriod)
        try container.encodeIfPresent(keyPrefix, forKey: .keyPrefix)
        try container.encode(name, forKey: .name)
        try container.encode(totals, forKey: .totals)
    }
}

