//
// ApiKeyUsageResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ApiKeyUsageResponse: Sendable, Codable, Hashable {

    public var keys: [ApiKeyUsageDetail]
    public var periodEnd: String
    public var periodStart: String

    public init(keys: [ApiKeyUsageDetail], periodEnd: String, periodStart: String) {
        self.keys = keys
        self.periodEnd = periodEnd
        self.periodStart = periodStart
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case keys
        case periodEnd
        case periodStart
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(keys, forKey: .keys)
        try container.encode(periodEnd, forKey: .periodEnd)
        try container.encode(periodStart, forKey: .periodStart)
    }
}

