//
// AsyncJobCreatedResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct AsyncJobCreatedResponse: Sendable, Codable, Hashable {

    public enum Status: String, Sendable, Codable, CaseIterable {
        case queued = "QUEUED"
        case processing = "PROCESSING"
        case completed = "COMPLETED"
        case failed = "FAILED"
        case cancelled = "CANCELLED"
    }
    public var createdAt: Date
    public var id: String
    public var status: Status
    public var statusUrl: String

    public init(createdAt: Date, id: String, status: Status, statusUrl: String) {
        self.createdAt = createdAt
        self.id = id
        self.status = status
        self.statusUrl = statusUrl
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case createdAt
        case id
        case status
        case statusUrl
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(createdAt, forKey: .createdAt)
        try container.encode(id, forKey: .id)
        try container.encode(status, forKey: .status)
        try container.encode(statusUrl, forKey: .statusUrl)
    }
}

