//
// BandwidthQuotaResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct BandwidthQuotaResponse: Sendable, Codable, Hashable {

    public var limitBytes: Int64
    public var limitFormatted: String
    public var percentUsed: Int
    public var remainingBytes: Int64
    public var remainingFormatted: String
    public var usedBytes: Int64
    public var usedFormatted: String

    public init(limitBytes: Int64, limitFormatted: String, percentUsed: Int, remainingBytes: Int64, remainingFormatted: String, usedBytes: Int64, usedFormatted: String) {
        self.limitBytes = limitBytes
        self.limitFormatted = limitFormatted
        self.percentUsed = percentUsed
        self.remainingBytes = remainingBytes
        self.remainingFormatted = remainingFormatted
        self.usedBytes = usedBytes
        self.usedFormatted = usedFormatted
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case limitBytes
        case limitFormatted
        case percentUsed
        case remainingBytes
        case remainingFormatted
        case usedBytes
        case usedFormatted
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(limitBytes, forKey: .limitBytes)
        try container.encode(limitFormatted, forKey: .limitFormatted)
        try container.encode(percentUsed, forKey: .percentUsed)
        try container.encode(remainingBytes, forKey: .remainingBytes)
        try container.encode(remainingFormatted, forKey: .remainingFormatted)
        try container.encode(usedBytes, forKey: .usedBytes)
        try container.encode(usedFormatted, forKey: .usedFormatted)
    }
}

