//
// BorderConfig.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct BorderConfig: Sendable, Codable, Hashable {

    public static let radiusRule = NumericRule<Int>(minimum: 0, exclusiveMinimum: false, maximum: 20, exclusiveMaximum: false, multipleOf: nil)
    public static let widthRule = NumericRule<Int>(minimum: 0, exclusiveMinimum: false, maximum: 10, exclusiveMaximum: false, multipleOf: nil)
    public var color: String? = "#cccccc"
    public var radius: Int? = 0
    public var width: Int? = 1

    public init(color: String? = "#cccccc", radius: Int? = 0, width: Int? = 1) {
        self.color = color
        self.radius = radius
        self.width = width
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case color
        case radius
        case width
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(color, forKey: .color)
        try container.encodeIfPresent(radius, forKey: .radius)
        try container.encodeIfPresent(width, forKey: .width)
    }
}

