//
// BrowserSessionRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct BrowserSessionRequest: Sendable, Codable, Hashable {

    public static let cookiesRule = ArrayRule(minItems: 0, maxItems: 200, uniqueItems: false)
    public static let headersRule = ArrayRule(minItems: 0, maxItems: 100, uniqueItems: false)
    public static let storageRule = ArrayRule(minItems: 0, maxItems: 5, uniqueItems: false)
    public var cookies: [BrowserCookieRequest]?
    public var headers: [BrowserHeaderRequest]?
    public var storage: [BrowserStorageOriginRequest]?

    public init(cookies: [BrowserCookieRequest]? = nil, headers: [BrowserHeaderRequest]? = nil, storage: [BrowserStorageOriginRequest]? = nil) {
        self.cookies = cookies
        self.headers = headers
        self.storage = storage
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case cookies
        case headers
        case storage
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(cookies, forKey: .cookies)
        try container.encodeIfPresent(headers, forKey: .headers)
        try container.encodeIfPresent(storage, forKey: .storage)
    }
}

