//
// BrowserCookieRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct BrowserCookieRequest: Sendable, Codable, Hashable {

    public static let domainRule = StringRule(minLength: 0, maxLength: 255, pattern: nil)
    public static let nameRule = StringRule(minLength: 0, maxLength: 512, pattern: nil)
    public static let pathRule = StringRule(minLength: 0, maxLength: 2048, pattern: nil)
    public static let sameSiteRule = StringRule(minLength: nil, maxLength: nil, pattern: "^(strict|lax|none|no_restriction|unspecified)$")
    public static let valueRule = StringRule(minLength: 0, maxLength: 4096, pattern: nil)
    public var domain: String?
    public var expires: Double?
    public var httpOnly: Bool?
    public var name: String
    public var path: String? = "/"
    public var sameSite: String?
    public var secure: Bool?
    public var value: String? = ""

    public init(domain: String? = nil, expires: Double? = nil, httpOnly: Bool? = nil, name: String, path: String? = "/", sameSite: String? = nil, secure: Bool? = nil, value: String? = "") {
        self.domain = domain
        self.expires = expires
        self.httpOnly = httpOnly
        self.name = name
        self.path = path
        self.sameSite = sameSite
        self.secure = secure
        self.value = value
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case domain
        case expires
        case httpOnly
        case name
        case path
        case sameSite
        case secure
        case value
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(domain, forKey: .domain)
        try container.encodeIfPresent(expires, forKey: .expires)
        try container.encodeIfPresent(httpOnly, forKey: .httpOnly)
        try container.encode(name, forKey: .name)
        try container.encodeIfPresent(path, forKey: .path)
        try container.encodeIfPresent(sameSite, forKey: .sameSite)
        try container.encodeIfPresent(secure, forKey: .secure)
        try container.encodeIfPresent(value, forKey: .value)
    }
}

