//
// BrowserHeaderRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct BrowserHeaderRequest: Sendable, Codable, Hashable {

    public static let nameRule = StringRule(minLength: 0, maxLength: 128, pattern: "^[!#$%&'*+.^_`|~0-9A-Za-z-]+$")
    public static let originRule = StringRule(minLength: 0, maxLength: 255, pattern: "^https?://[^/]+$")
    public static let valueRule = StringRule(minLength: 0, maxLength: 8192, pattern: "^[^\\r\\n]*$")
    public var name: String
    public var origin: String?
    public var value: String? = ""

    public init(name: String, origin: String? = nil, value: String? = "") {
        self.name = name
        self.origin = origin
        self.value = value
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case origin
        case value
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(name, forKey: .name)
        try container.encodeIfPresent(origin, forKey: .origin)
        try container.encodeIfPresent(value, forKey: .value)
    }
}

