//
// BrowserStorageOriginRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct BrowserStorageOriginRequest: Sendable, Codable, Hashable {

    public static let originRule = StringRule(minLength: 0, maxLength: 255, pattern: "^https?://[^/]+$")
    public var localStorage: [String: String]?
    public var origin: String
    public var sessionStorage: [String: String]?

    public init(localStorage: [String: String]? = nil, origin: String, sessionStorage: [String: String]? = nil) {
        self.localStorage = localStorage
        self.origin = origin
        self.sessionStorage = sessionStorage
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case localStorage
        case origin
        case sessionStorage
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(localStorage, forKey: .localStorage)
        try container.encode(origin, forKey: .origin)
        try container.encodeIfPresent(sessionStorage, forKey: .sessionStorage)
    }
}

