//
// BulkUrlRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct BulkUrlRequest: Sendable, Codable, Hashable {

    public static let urlRule = StringRule(minLength: nil, maxLength: nil, pattern: "^https?://.*")
    public var options: BulkUrlOptions?
    public var url: String

    public init(options: BulkUrlOptions? = nil, url: String) {
        self.options = options
        self.url = url
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case options
        case url
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(options, forKey: .options)
        try container.encode(url, forKey: .url)
    }
}

