//
// BulkResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct BulkResponse: Sendable, Codable, Hashable {

    public var completedAt: Date?
    public var completedJobs: Int
    public var createdAt: Date
    public var failedJobs: Int
    public var id: String
    public var jobs: [BulkJobInfo]
    public var progress: Int
    public var status: String
    public var totalJobs: Int

    public init(completedAt: Date? = nil, completedJobs: Int, createdAt: Date, failedJobs: Int, id: String, jobs: [BulkJobInfo], progress: Int, status: String, totalJobs: Int) {
        self.completedAt = completedAt
        self.completedJobs = completedJobs
        self.createdAt = createdAt
        self.failedJobs = failedJobs
        self.id = id
        self.jobs = jobs
        self.progress = progress
        self.status = status
        self.totalJobs = totalJobs
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case completedAt
        case completedJobs
        case createdAt
        case failedJobs
        case id
        case jobs
        case progress
        case status
        case totalJobs
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(completedAt, forKey: .completedAt)
        try container.encode(completedJobs, forKey: .completedJobs)
        try container.encode(createdAt, forKey: .createdAt)
        try container.encode(failedJobs, forKey: .failedJobs)
        try container.encode(id, forKey: .id)
        try container.encode(jobs, forKey: .jobs)
        try container.encode(progress, forKey: .progress)
        try container.encode(status, forKey: .status)
        try container.encode(totalJobs, forKey: .totalJobs)
    }
}

