//
// BulkUrlOptions.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct BulkUrlOptions: Sendable, Codable, Hashable {

    public static let blockLevelRule = StringRule(minLength: nil, maxLength: nil, pattern: "^(none|light|normal|pro|pro_plus|ultimate)$")
    public static let customCssRule = StringRule(minLength: 0, maxLength: 10000, pattern: nil)
    public static let delayRule = NumericRule<Int>(minimum: 0, exclusiveMinimum: false, maximum: 30000, exclusiveMaximum: false, multipleOf: nil)
    public static let formatRule = StringRule(minLength: nil, maxLength: nil, pattern: "^(png|jpeg|jpg|webp|pdf)$")
    public static let qualityRule = NumericRule<Int>(minimum: 1, exclusiveMinimum: false, maximum: 100, exclusiveMaximum: false, multipleOf: nil)
    public static let waitUntilRule = StringRule(minLength: nil, maxLength: nil, pattern: "^(load|domcontentloaded|networkidle)$")
    public var actions: [PageAction]?
    public var blockAds: Bool?
    public var blockCookieBanners: Bool?
    public var blockLevel: String?
    public var blockPopups: Bool?
    public var customCss: String?
    public var darkMode: Bool?
    public var delay: Int?
    public var device: String?
    public var format: String?
    public var fullPage: Bool?
    public var outputs: [OutputSpec]?
    public var quality: Int?
    public var stealthMode: Bool?
    public var viewport: ViewportConfig?
    public var waitFor: String?
    public var waitUntil: String?

    public init(actions: [PageAction]? = nil, blockAds: Bool? = nil, blockCookieBanners: Bool? = nil, blockLevel: String? = nil, blockPopups: Bool? = nil, customCss: String? = nil, darkMode: Bool? = nil, delay: Int? = nil, device: String? = nil, format: String? = nil, fullPage: Bool? = nil, outputs: [OutputSpec]? = nil, quality: Int? = nil, stealthMode: Bool? = nil, viewport: ViewportConfig? = nil, waitFor: String? = nil, waitUntil: String? = nil) {
        self.actions = actions
        self.blockAds = blockAds
        self.blockCookieBanners = blockCookieBanners
        self.blockLevel = blockLevel
        self.blockPopups = blockPopups
        self.customCss = customCss
        self.darkMode = darkMode
        self.delay = delay
        self.device = device
        self.format = format
        self.fullPage = fullPage
        self.outputs = outputs
        self.quality = quality
        self.stealthMode = stealthMode
        self.viewport = viewport
        self.waitFor = waitFor
        self.waitUntil = waitUntil
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case actions
        case blockAds
        case blockCookieBanners
        case blockLevel
        case blockPopups
        case customCss
        case darkMode
        case delay
        case device
        case format
        case fullPage
        case outputs
        case quality
        case stealthMode
        case viewport
        case waitFor
        case waitUntil
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(actions, forKey: .actions)
        try container.encodeIfPresent(blockAds, forKey: .blockAds)
        try container.encodeIfPresent(blockCookieBanners, forKey: .blockCookieBanners)
        try container.encodeIfPresent(blockLevel, forKey: .blockLevel)
        try container.encodeIfPresent(blockPopups, forKey: .blockPopups)
        try container.encodeIfPresent(customCss, forKey: .customCss)
        try container.encodeIfPresent(darkMode, forKey: .darkMode)
        try container.encodeIfPresent(delay, forKey: .delay)
        try container.encodeIfPresent(device, forKey: .device)
        try container.encodeIfPresent(format, forKey: .format)
        try container.encodeIfPresent(fullPage, forKey: .fullPage)
        try container.encodeIfPresent(outputs, forKey: .outputs)
        try container.encodeIfPresent(quality, forKey: .quality)
        try container.encodeIfPresent(stealthMode, forKey: .stealthMode)
        try container.encodeIfPresent(viewport, forKey: .viewport)
        try container.encodeIfPresent(waitFor, forKey: .waitFor)
        try container.encodeIfPresent(waitUntil, forKey: .waitUntil)
    }
}

