//
// BulkJobDetailInfo.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct BulkJobDetailInfo: Sendable, Codable, Hashable {

    public var completedAt: Date?
    public var createdAt: Date
    public var errorCode: String?
    public var errorMessage: String?
    public var fileSize: Int64?
    public var format: String?
    public var height: Int?
    public var id: String
    public var renderTimeMs: Int64?
    public var resultUrl: String?
    public var status: String
    public var storageUrl: String?
    public var url: String
    public var width: Int?

    public init(completedAt: Date? = nil, createdAt: Date, errorCode: String? = nil, errorMessage: String? = nil, fileSize: Int64? = nil, format: String? = nil, height: Int? = nil, id: String, renderTimeMs: Int64? = nil, resultUrl: String? = nil, status: String, storageUrl: String? = nil, url: String, width: Int? = nil) {
        self.completedAt = completedAt
        self.createdAt = createdAt
        self.errorCode = errorCode
        self.errorMessage = errorMessage
        self.fileSize = fileSize
        self.format = format
        self.height = height
        self.id = id
        self.renderTimeMs = renderTimeMs
        self.resultUrl = resultUrl
        self.status = status
        self.storageUrl = storageUrl
        self.url = url
        self.width = width
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case completedAt
        case createdAt
        case errorCode
        case errorMessage
        case fileSize
        case format
        case height
        case id
        case renderTimeMs
        case resultUrl
        case status
        case storageUrl
        case url
        case width
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(completedAt, forKey: .completedAt)
        try container.encode(createdAt, forKey: .createdAt)
        try container.encodeIfPresent(errorCode, forKey: .errorCode)
        try container.encodeIfPresent(errorMessage, forKey: .errorMessage)
        try container.encodeIfPresent(fileSize, forKey: .fileSize)
        try container.encodeIfPresent(format, forKey: .format)
        try container.encodeIfPresent(height, forKey: .height)
        try container.encode(id, forKey: .id)
        try container.encodeIfPresent(renderTimeMs, forKey: .renderTimeMs)
        try container.encodeIfPresent(resultUrl, forKey: .resultUrl)
        try container.encode(status, forKey: .status)
        try container.encodeIfPresent(storageUrl, forKey: .storageUrl)
        try container.encode(url, forKey: .url)
        try container.encodeIfPresent(width, forKey: .width)
    }
}

