//
// BulkJobInfo.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct BulkJobInfo: Sendable, Codable, Hashable {

    public var errorCode: String?
    public var errorMessage: String?
    public var id: String
    public var resultUrl: String?
    public var status: String
    public var url: String

    public init(errorCode: String? = nil, errorMessage: String? = nil, id: String, resultUrl: String? = nil, status: String, url: String) {
        self.errorCode = errorCode
        self.errorMessage = errorMessage
        self.id = id
        self.resultUrl = resultUrl
        self.status = status
        self.url = url
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case errorCode
        case errorMessage
        case id
        case resultUrl
        case status
        case url
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(errorCode, forKey: .errorCode)
        try container.encodeIfPresent(errorMessage, forKey: .errorMessage)
        try container.encode(id, forKey: .id)
        try container.encodeIfPresent(resultUrl, forKey: .resultUrl)
        try container.encode(status, forKey: .status)
        try container.encode(url, forKey: .url)
    }
}

