//
// BulkRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct BulkRequest: Sendable, Codable, Hashable {

    public static let urlsRule = ArrayRule(minItems: 0, maxItems: 100, uniqueItems: false)
    public static let webhookSecretRule = StringRule(minLength: 0, maxLength: 255, pattern: nil)
    public static let webhookUrlRule = StringRule(minLength: nil, maxLength: nil, pattern: "^https?://.*")
    public var defaults: BulkDefaults?
    public var urls: [BulkUrlRequest]
    public var webhookSecret: String?
    public var webhookUrl: String?

    public init(defaults: BulkDefaults? = nil, urls: [BulkUrlRequest], webhookSecret: String? = nil, webhookUrl: String? = nil) {
        self.defaults = defaults
        self.urls = urls
        self.webhookSecret = webhookSecret
        self.webhookUrl = webhookUrl
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case defaults
        case urls
        case webhookSecret
        case webhookUrl
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(defaults, forKey: .defaults)
        try container.encode(urls, forKey: .urls)
        try container.encodeIfPresent(webhookSecret, forKey: .webhookSecret)
        try container.encodeIfPresent(webhookUrl, forKey: .webhookUrl)
    }
}

