//
// CaptureDefaults.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct CaptureDefaults: Sendable, Codable, Hashable {

    public var actions: [PageAction]?
    public var blockAds: Bool? = true
    public var blockCookieBanners: Bool? = true
    public var blockLevel: String? = "none"
    public var blockPopups: Bool? = true
    public var customCss: String?
    public var darkMode: Bool? = false
    public var delay: Int? = 0
    public var device: String?
    public var format: String? = "png"
    public var fullPage: Bool? = false
    public var hideSelectors: [String]?
    public var quality: Int? = 80
    public var stealthMode: Bool? = false
    public var timeout: Int? = 30000
    public var viewport: ViewportConfig?
    public var waitFor: String?
    public var waitUntil: String? = "domcontentloaded"

    public init(actions: [PageAction]? = nil, blockAds: Bool? = true, blockCookieBanners: Bool? = true, blockLevel: String? = "none", blockPopups: Bool? = true, customCss: String? = nil, darkMode: Bool? = false, delay: Int? = 0, device: String? = nil, format: String? = "png", fullPage: Bool? = false, hideSelectors: [String]? = nil, quality: Int? = 80, stealthMode: Bool? = false, timeout: Int? = 30000, viewport: ViewportConfig? = nil, waitFor: String? = nil, waitUntil: String? = "domcontentloaded") {
        self.actions = actions
        self.blockAds = blockAds
        self.blockCookieBanners = blockCookieBanners
        self.blockLevel = blockLevel
        self.blockPopups = blockPopups
        self.customCss = customCss
        self.darkMode = darkMode
        self.delay = delay
        self.device = device
        self.format = format
        self.fullPage = fullPage
        self.hideSelectors = hideSelectors
        self.quality = quality
        self.stealthMode = stealthMode
        self.timeout = timeout
        self.viewport = viewport
        self.waitFor = waitFor
        self.waitUntil = waitUntil
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case actions
        case blockAds
        case blockCookieBanners
        case blockLevel
        case blockPopups
        case customCss
        case darkMode
        case delay
        case device
        case format
        case fullPage
        case hideSelectors
        case quality
        case stealthMode
        case timeout
        case viewport
        case waitFor
        case waitUntil
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(actions, forKey: .actions)
        try container.encodeIfPresent(blockAds, forKey: .blockAds)
        try container.encodeIfPresent(blockCookieBanners, forKey: .blockCookieBanners)
        try container.encodeIfPresent(blockLevel, forKey: .blockLevel)
        try container.encodeIfPresent(blockPopups, forKey: .blockPopups)
        try container.encodeIfPresent(customCss, forKey: .customCss)
        try container.encodeIfPresent(darkMode, forKey: .darkMode)
        try container.encodeIfPresent(delay, forKey: .delay)
        try container.encodeIfPresent(device, forKey: .device)
        try container.encodeIfPresent(format, forKey: .format)
        try container.encodeIfPresent(fullPage, forKey: .fullPage)
        try container.encodeIfPresent(hideSelectors, forKey: .hideSelectors)
        try container.encodeIfPresent(quality, forKey: .quality)
        try container.encodeIfPresent(stealthMode, forKey: .stealthMode)
        try container.encodeIfPresent(timeout, forKey: .timeout)
        try container.encodeIfPresent(viewport, forKey: .viewport)
        try container.encodeIfPresent(waitFor, forKey: .waitFor)
        try container.encodeIfPresent(waitUntil, forKey: .waitUntil)
    }
}

