//
// CaptureInfo.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct CaptureInfo: Sendable, Codable, Hashable {

    public var height: Int
    public var id: String
    public var label: String?
    public var originalHeight: Int
    public var originalWidth: Int
    public var url: String
    public var width: Int
    public var x: Int
    public var y: Int

    public init(height: Int, id: String, label: String? = nil, originalHeight: Int, originalWidth: Int, url: String, width: Int, x: Int, y: Int) {
        self.height = height
        self.id = id
        self.label = label
        self.originalHeight = originalHeight
        self.originalWidth = originalWidth
        self.url = url
        self.width = width
        self.x = x
        self.y = y
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case height
        case id
        case label
        case originalHeight
        case originalWidth
        case url
        case width
        case x
        case y
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(height, forKey: .height)
        try container.encode(id, forKey: .id)
        try container.encodeIfPresent(label, forKey: .label)
        try container.encode(originalHeight, forKey: .originalHeight)
        try container.encode(originalWidth, forKey: .originalWidth)
        try container.encode(url, forKey: .url)
        try container.encode(width, forKey: .width)
        try container.encode(x, forKey: .x)
        try container.encode(y, forKey: .y)
    }
}

