//
// ComposeJobStatusResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ComposeJobStatusResponse: Sendable, Codable, Hashable {

    public var completedAt: Date?
    public var completedCaptures: Int
    public var createdAt: Date
    public var errorCode: String?
    public var errorMessage: String?
    public var jobId: String
    public var progress: Int
    public var result: ComposeResponse?
    public var status: String
    public var totalCaptures: Int

    public init(completedAt: Date? = nil, completedCaptures: Int, createdAt: Date, errorCode: String? = nil, errorMessage: String? = nil, jobId: String, progress: Int, result: ComposeResponse? = nil, status: String, totalCaptures: Int) {
        self.completedAt = completedAt
        self.completedCaptures = completedCaptures
        self.createdAt = createdAt
        self.errorCode = errorCode
        self.errorMessage = errorMessage
        self.jobId = jobId
        self.progress = progress
        self.result = result
        self.status = status
        self.totalCaptures = totalCaptures
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case completedAt
        case completedCaptures
        case createdAt
        case errorCode
        case errorMessage
        case jobId
        case progress
        case result
        case status
        case totalCaptures
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(completedAt, forKey: .completedAt)
        try container.encode(completedCaptures, forKey: .completedCaptures)
        try container.encode(createdAt, forKey: .createdAt)
        try container.encodeIfPresent(errorCode, forKey: .errorCode)
        try container.encodeIfPresent(errorMessage, forKey: .errorMessage)
        try container.encode(jobId, forKey: .jobId)
        try container.encode(progress, forKey: .progress)
        try container.encodeIfPresent(result, forKey: .result)
        try container.encode(status, forKey: .status)
        try container.encode(totalCaptures, forKey: .totalCaptures)
    }
}

