//
// ComposeRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ComposeRequest: Sendable, Codable, Hashable {

    public static let capturesRule = ArrayRule(minItems: 0, maxItems: 20, uniqueItems: false)
    public static let urlRule = StringRule(minLength: nil, maxLength: nil, pattern: "^https?://.*")
    public static let variantsRule = ArrayRule(minItems: 0, maxItems: 20, uniqueItems: false)
    public static let webhookSecretRule = StringRule(minLength: 0, maxLength: 255, pattern: nil)
    public static let webhookUrlRule = StringRule(minLength: nil, maxLength: nil, pattern: "^https?://.*")
    public var async: Bool?
    public var captures: [CaptureItem]?
    public var capturesMode: Bool?
    public var defaults: CaptureDefaults?
    public var output: ComposeOutputConfig?
    public var url: String?
    public var variants: [VariantConfig]?
    public var variantsMode: Bool?
    public var webhookSecret: String?
    public var webhookUrl: String?

    public init(async: Bool? = nil, captures: [CaptureItem]? = nil, capturesMode: Bool? = nil, defaults: CaptureDefaults? = nil, output: ComposeOutputConfig? = nil, url: String? = nil, variants: [VariantConfig]? = nil, variantsMode: Bool? = nil, webhookSecret: String? = nil, webhookUrl: String? = nil) {
        self.async = async
        self.captures = captures
        self.capturesMode = capturesMode
        self.defaults = defaults
        self.output = output
        self.url = url
        self.variants = variants
        self.variantsMode = variantsMode
        self.webhookSecret = webhookSecret
        self.webhookUrl = webhookUrl
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case async
        case captures
        case capturesMode
        case defaults
        case output
        case url
        case variants
        case variantsMode
        case webhookSecret
        case webhookUrl
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(async, forKey: .async)
        try container.encodeIfPresent(captures, forKey: .captures)
        try container.encodeIfPresent(capturesMode, forKey: .capturesMode)
        try container.encodeIfPresent(defaults, forKey: .defaults)
        try container.encodeIfPresent(output, forKey: .output)
        try container.encodeIfPresent(url, forKey: .url)
        try container.encodeIfPresent(variants, forKey: .variants)
        try container.encodeIfPresent(variantsMode, forKey: .variantsMode)
        try container.encodeIfPresent(webhookSecret, forKey: .webhookSecret)
        try container.encodeIfPresent(webhookUrl, forKey: .webhookUrl)
    }
}

