//
// ComposeJobSummaryResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ComposeJobSummaryResponse: Sendable, Codable, Hashable {

    public var completedAt: Date?
    public var completedCaptures: Int
    public var createdAt: Date
    public var failedCaptures: Int
    public var jobId: String
    public var layoutType: String
    public var progress: Int
    public var status: String
    public var totalCaptures: Int

    public init(completedAt: Date? = nil, completedCaptures: Int, createdAt: Date, failedCaptures: Int, jobId: String, layoutType: String, progress: Int, status: String, totalCaptures: Int) {
        self.completedAt = completedAt
        self.completedCaptures = completedCaptures
        self.createdAt = createdAt
        self.failedCaptures = failedCaptures
        self.jobId = jobId
        self.layoutType = layoutType
        self.progress = progress
        self.status = status
        self.totalCaptures = totalCaptures
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case completedAt
        case completedCaptures
        case createdAt
        case failedCaptures
        case jobId
        case layoutType
        case progress
        case status
        case totalCaptures
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(completedAt, forKey: .completedAt)
        try container.encode(completedCaptures, forKey: .completedCaptures)
        try container.encode(createdAt, forKey: .createdAt)
        try container.encode(failedCaptures, forKey: .failedCaptures)
        try container.encode(jobId, forKey: .jobId)
        try container.encode(layoutType, forKey: .layoutType)
        try container.encode(progress, forKey: .progress)
        try container.encode(status, forKey: .status)
        try container.encode(totalCaptures, forKey: .totalCaptures)
    }
}

