//
// ComposeJobCreatedResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ComposeJobCreatedResponse: Sendable, Codable, Hashable {

    public var createdAt: Date
    public var jobId: String
    public var status: String
    public var statusUrl: String

    public init(createdAt: Date, jobId: String, status: String, statusUrl: String) {
        self.createdAt = createdAt
        self.jobId = jobId
        self.status = status
        self.statusUrl = statusUrl
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case createdAt
        case jobId
        case status
        case statusUrl
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(createdAt, forKey: .createdAt)
        try container.encode(jobId, forKey: .jobId)
        try container.encode(status, forKey: .status)
        try container.encode(statusUrl, forKey: .statusUrl)
    }
}

