//
// ComposeResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ComposeResponse: Sendable, Codable, Hashable {

    public var expiresAt: Date
    public var fileSize: Int64
    public var format: String
    public var height: Int
    public var layout: String
    public var metadata: ComposeMetadata
    public var renderTimeMs: Int64
    public var storageUrl: String?
    public var url: String
    public var width: Int

    public init(expiresAt: Date, fileSize: Int64, format: String, height: Int, layout: String, metadata: ComposeMetadata, renderTimeMs: Int64, storageUrl: String? = nil, url: String, width: Int) {
        self.expiresAt = expiresAt
        self.fileSize = fileSize
        self.format = format
        self.height = height
        self.layout = layout
        self.metadata = metadata
        self.renderTimeMs = renderTimeMs
        self.storageUrl = storageUrl
        self.url = url
        self.width = width
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case expiresAt
        case fileSize
        case format
        case height
        case layout
        case metadata
        case renderTimeMs
        case storageUrl
        case url
        case width
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(expiresAt, forKey: .expiresAt)
        try container.encode(fileSize, forKey: .fileSize)
        try container.encode(format, forKey: .format)
        try container.encode(height, forKey: .height)
        try container.encode(layout, forKey: .layout)
        try container.encode(metadata, forKey: .metadata)
        try container.encode(renderTimeMs, forKey: .renderTimeMs)
        try container.encodeIfPresent(storageUrl, forKey: .storageUrl)
        try container.encode(url, forKey: .url)
        try container.encode(width, forKey: .width)
    }
}

