//
// ComposeMetadata.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ComposeMetadata: Sendable, Codable, Hashable {

    public var canvasHeight: Int
    public var canvasWidth: Int
    public var captures: [CaptureInfo]
    public var layoutType: String
    public var totalCaptures: Int

    public init(canvasHeight: Int, canvasWidth: Int, captures: [CaptureInfo], layoutType: String, totalCaptures: Int) {
        self.canvasHeight = canvasHeight
        self.canvasWidth = canvasWidth
        self.captures = captures
        self.layoutType = layoutType
        self.totalCaptures = totalCaptures
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case canvasHeight
        case canvasWidth
        case captures
        case layoutType
        case totalCaptures
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(canvasHeight, forKey: .canvasHeight)
        try container.encode(canvasWidth, forKey: .canvasWidth)
        try container.encode(captures, forKey: .captures)
        try container.encode(layoutType, forKey: .layoutType)
        try container.encode(totalCaptures, forKey: .totalCaptures)
    }
}

