//
// ComposeOutputConfig.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ComposeOutputConfig: Sendable, Codable, Hashable {

    public enum Layout: String, Sendable, Codable, CaseIterable {
        case grid = "GRID"
        case horizontal = "HORIZONTAL"
        case vertical = "VERTICAL"
        case masonry = "MASONRY"
        case mondrian = "MONDRIAN"
        case partitioning = "PARTITIONING"
        case auto = "AUTO"
    }
    public static let alignmentRule = StringRule(minLength: nil, maxLength: nil, pattern: "^(top|center|bottom)$")
    public static let backgroundRule = StringRule(minLength: nil, maxLength: nil, pattern: "^(#[0-9A-Fa-f]{6}|#[0-9A-Fa-f]{8}|transparent)$")
    public static let columnsRule = NumericRule<Int>(minimum: 1, exclusiveMinimum: false, maximum: 10, exclusiveMaximum: false, multipleOf: nil)
    public static let formatRule = StringRule(minLength: nil, maxLength: nil, pattern: "^(png|jpeg|jpg|webp)$")
    public static let maxHeightRule = NumericRule<Int>(minimum: 100, exclusiveMinimum: false, maximum: 10000, exclusiveMaximum: false, multipleOf: nil)
    public static let maxWidthRule = NumericRule<Int>(minimum: 100, exclusiveMinimum: false, maximum: 10000, exclusiveMaximum: false, multipleOf: nil)
    public static let paddingRule = NumericRule<Int>(minimum: 0, exclusiveMinimum: false, maximum: 100, exclusiveMaximum: false, multipleOf: nil)
    public static let qualityRule = NumericRule<Int>(minimum: 1, exclusiveMinimum: false, maximum: 100, exclusiveMaximum: false, multipleOf: nil)
    public static let spacingRule = NumericRule<Int>(minimum: 0, exclusiveMinimum: false, maximum: 100, exclusiveMaximum: false, multipleOf: nil)
    public static let thumbnailWidthRule = NumericRule<Int>(minimum: 50, exclusiveMinimum: false, maximum: 2000, exclusiveMaximum: false, multipleOf: nil)
    public var alignment: String? = "center"
    public var background: String? = "#ffffff"
    public var border: BorderConfig?
    public var columns: Int?
    public var format: String? = "png"
    public var labels: LabelConfig?
    public var layout: Layout? = .auto
    public var maxHeight: Int?
    public var maxWidth: Int?
    public var padding: Int? = 0
    public var quality: Int? = 90
    public var shadow: ShadowConfig?
    public var spacing: Int? = 10
    public var thumbnailWidth: Int?

    public init(alignment: String? = "center", background: String? = "#ffffff", border: BorderConfig? = nil, columns: Int? = nil, format: String? = "png", labels: LabelConfig? = nil, layout: Layout? = .auto, maxHeight: Int? = nil, maxWidth: Int? = nil, padding: Int? = 0, quality: Int? = 90, shadow: ShadowConfig? = nil, spacing: Int? = 10, thumbnailWidth: Int? = nil) {
        self.alignment = alignment
        self.background = background
        self.border = border
        self.columns = columns
        self.format = format
        self.labels = labels
        self.layout = layout
        self.maxHeight = maxHeight
        self.maxWidth = maxWidth
        self.padding = padding
        self.quality = quality
        self.shadow = shadow
        self.spacing = spacing
        self.thumbnailWidth = thumbnailWidth
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case alignment
        case background
        case border
        case columns
        case format
        case labels
        case layout
        case maxHeight
        case maxWidth
        case padding
        case quality
        case shadow
        case spacing
        case thumbnailWidth
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(alignment, forKey: .alignment)
        try container.encodeIfPresent(background, forKey: .background)
        try container.encodeIfPresent(border, forKey: .border)
        try container.encodeIfPresent(columns, forKey: .columns)
        try container.encodeIfPresent(format, forKey: .format)
        try container.encodeIfPresent(labels, forKey: .labels)
        try container.encodeIfPresent(layout, forKey: .layout)
        try container.encodeIfPresent(maxHeight, forKey: .maxHeight)
        try container.encodeIfPresent(maxWidth, forKey: .maxWidth)
        try container.encodeIfPresent(padding, forKey: .padding)
        try container.encodeIfPresent(quality, forKey: .quality)
        try container.encodeIfPresent(shadow, forKey: .shadow)
        try container.encodeIfPresent(spacing, forKey: .spacing)
        try container.encodeIfPresent(thumbnailWidth, forKey: .thumbnailWidth)
    }
}

