//
// CrawlRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct CrawlRequest: Sendable, Codable, Hashable {

    public static let crawlDelayMsRule = NumericRule<Int>(minimum: 500, exclusiveMinimum: false, maximum: 30000, exclusiveMaximum: false, multipleOf: nil)
    public static let depthRule = NumericRule<Int>(minimum: 0, exclusiveMinimum: false, maximum: 5, exclusiveMaximum: false, multipleOf: nil)
    public static let excludePatternsRule = ArrayRule(minItems: 0, maxItems: 25, uniqueItems: false)
    public static let formatRule = StringRule(minLength: nil, maxLength: nil, pattern: "^(png|jpeg|jpg)$")
    public static let includePatternsRule = ArrayRule(minItems: 0, maxItems: 25, uniqueItems: false)
    public static let limitRule = NumericRule<Int>(minimum: 1, exclusiveMinimum: false, maximum: 100, exclusiveMaximum: false, multipleOf: nil)
    public static let outputsRule = ArrayRule(minItems: 1, maxItems: 4, uniqueItems: true)
    public static let qualityRule = NumericRule<Int>(minimum: 1, exclusiveMinimum: false, maximum: 100, exclusiveMaximum: false, multipleOf: nil)
    public static let renderDelayRule = NumericRule<Int>(minimum: 0, exclusiveMinimum: false, maximum: 30000, exclusiveMaximum: false, multipleOf: nil)
    public static let timeoutRule = NumericRule<Int>(minimum: 1000, exclusiveMinimum: false, maximum: 60000, exclusiveMaximum: false, multipleOf: nil)
    public static let urlRule = StringRule(minLength: 1, maxLength: nil, pattern: "^https?://.*")
    public static let waitUntilRule = StringRule(minLength: nil, maxLength: nil, pattern: "^(load|domcontentloaded|networkidle)$")
    public var blockAds: Bool? = true
    public var blockCookieBanners: Bool? = true
    public var blockPopups: Bool? = true
    public var crawlDelayMs: Int? = 500
    public var darkMode: Bool? = false
    public var depth: Int? = 2
    public var excludePatterns: [String]?
    public var format: String? = "png"
    public var fullPage: Bool? = true
    public var includePatterns: [String]?
    public var includeSubdomains: Bool? = false
    public var limit: Int? = 25
    public var outputs: Set<OutputSpec>?
    public var quality: Int? = 80
    public var renderDelay: Int? = 0
    public var timeout: Int? = 30000
    public var url: String
    public var viewport: ViewportConfig?
    public var waitUntil: String? = "domcontentloaded"

    public init(blockAds: Bool? = true, blockCookieBanners: Bool? = true, blockPopups: Bool? = true, crawlDelayMs: Int? = 500, darkMode: Bool? = false, depth: Int? = 2, excludePatterns: [String]? = nil, format: String? = "png", fullPage: Bool? = true, includePatterns: [String]? = nil, includeSubdomains: Bool? = false, limit: Int? = 25, outputs: Set<OutputSpec>? = nil, quality: Int? = 80, renderDelay: Int? = 0, timeout: Int? = 30000, url: String, viewport: ViewportConfig? = nil, waitUntil: String? = "domcontentloaded") {
        self.blockAds = blockAds
        self.blockCookieBanners = blockCookieBanners
        self.blockPopups = blockPopups
        self.crawlDelayMs = crawlDelayMs
        self.darkMode = darkMode
        self.depth = depth
        self.excludePatterns = excludePatterns
        self.format = format
        self.fullPage = fullPage
        self.includePatterns = includePatterns
        self.includeSubdomains = includeSubdomains
        self.limit = limit
        self.outputs = outputs
        self.quality = quality
        self.renderDelay = renderDelay
        self.timeout = timeout
        self.url = url
        self.viewport = viewport
        self.waitUntil = waitUntil
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case blockAds
        case blockCookieBanners
        case blockPopups
        case crawlDelayMs
        case darkMode
        case depth
        case excludePatterns
        case format
        case fullPage
        case includePatterns
        case includeSubdomains
        case limit
        case outputs
        case quality
        case renderDelay
        case timeout
        case url
        case viewport
        case waitUntil
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(blockAds, forKey: .blockAds)
        try container.encodeIfPresent(blockCookieBanners, forKey: .blockCookieBanners)
        try container.encodeIfPresent(blockPopups, forKey: .blockPopups)
        try container.encodeIfPresent(crawlDelayMs, forKey: .crawlDelayMs)
        try container.encodeIfPresent(darkMode, forKey: .darkMode)
        try container.encodeIfPresent(depth, forKey: .depth)
        try container.encodeIfPresent(excludePatterns, forKey: .excludePatterns)
        try container.encodeIfPresent(format, forKey: .format)
        try container.encodeIfPresent(fullPage, forKey: .fullPage)
        try container.encodeIfPresent(includePatterns, forKey: .includePatterns)
        try container.encodeIfPresent(includeSubdomains, forKey: .includeSubdomains)
        try container.encodeIfPresent(limit, forKey: .limit)
        try container.encodeIfPresent(outputs, forKey: .outputs)
        try container.encodeIfPresent(quality, forKey: .quality)
        try container.encodeIfPresent(renderDelay, forKey: .renderDelay)
        try container.encodeIfPresent(timeout, forKey: .timeout)
        try container.encode(url, forKey: .url)
        try container.encodeIfPresent(viewport, forKey: .viewport)
        try container.encodeIfPresent(waitUntil, forKey: .waitUntil)
    }
}

