//
// CrawlPageResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct CrawlPageResponse: Sendable, Codable, Hashable {

    public enum Status: String, Sendable, Codable, CaseIterable {
        case queued = "QUEUED"
        case running = "RUNNING"
        case completed = "COMPLETED"
        case failed = "FAILED"
        case skipped = "SKIPPED"
        case cancelled = "CANCELLED"
    }
    public var canonicalUrl: String?
    public var completedAt: Date?
    public var contentType: String?
    public var createdAt: Date
    public var depth: Int
    public var description: String?
    public var errorCode: String?
    public var errorMessage: String?
    public var httpStatus: Int?
    public var id: String
    public var language: String?
    public var outputs: [OutputSpec]
    public var parentId: String?
    public var renderTimeMs: Int64?
    public var status: Status
    public var title: String?
    public var url: String

    public init(canonicalUrl: String? = nil, completedAt: Date? = nil, contentType: String? = nil, createdAt: Date, depth: Int, description: String? = nil, errorCode: String? = nil, errorMessage: String? = nil, httpStatus: Int? = nil, id: String, language: String? = nil, outputs: [OutputSpec], parentId: String? = nil, renderTimeMs: Int64? = nil, status: Status, title: String? = nil, url: String) {
        self.canonicalUrl = canonicalUrl
        self.completedAt = completedAt
        self.contentType = contentType
        self.createdAt = createdAt
        self.depth = depth
        self.description = description
        self.errorCode = errorCode
        self.errorMessage = errorMessage
        self.httpStatus = httpStatus
        self.id = id
        self.language = language
        self.outputs = outputs
        self.parentId = parentId
        self.renderTimeMs = renderTimeMs
        self.status = status
        self.title = title
        self.url = url
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case canonicalUrl
        case completedAt
        case contentType
        case createdAt
        case depth
        case description
        case errorCode
        case errorMessage
        case httpStatus
        case id
        case language
        case outputs
        case parentId
        case renderTimeMs
        case status
        case title
        case url
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(canonicalUrl, forKey: .canonicalUrl)
        try container.encodeIfPresent(completedAt, forKey: .completedAt)
        try container.encodeIfPresent(contentType, forKey: .contentType)
        try container.encode(createdAt, forKey: .createdAt)
        try container.encode(depth, forKey: .depth)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encodeIfPresent(errorCode, forKey: .errorCode)
        try container.encodeIfPresent(errorMessage, forKey: .errorMessage)
        try container.encodeIfPresent(httpStatus, forKey: .httpStatus)
        try container.encode(id, forKey: .id)
        try container.encodeIfPresent(language, forKey: .language)
        try container.encode(outputs, forKey: .outputs)
        try container.encodeIfPresent(parentId, forKey: .parentId)
        try container.encodeIfPresent(renderTimeMs, forKey: .renderTimeMs)
        try container.encode(status, forKey: .status)
        try container.encodeIfPresent(title, forKey: .title)
        try container.encode(url, forKey: .url)
    }
}

