//
// CrawlPagesResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct CrawlPagesResponse: Sendable, Codable, Hashable {

    public var page: Int
    public var pageSize: Int
    public var pages: [CrawlPageResponse]
    public var total: Int64
    public var totalPages: Int

    public init(page: Int, pageSize: Int, pages: [CrawlPageResponse], total: Int64, totalPages: Int) {
        self.page = page
        self.pageSize = pageSize
        self.pages = pages
        self.total = total
        self.totalPages = totalPages
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case page
        case pageSize
        case pages
        case total
        case totalPages
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(page, forKey: .page)
        try container.encode(pageSize, forKey: .pageSize)
        try container.encode(pages, forKey: .pages)
        try container.encode(total, forKey: .total)
        try container.encode(totalPages, forKey: .totalPages)
    }
}

