//
// CrawlListResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct CrawlListResponse: Sendable, Codable, Hashable {

    public var crawls: [CrawlResponse]
    public var page: Int
    public var pageSize: Int
    public var total: Int64
    public var totalPages: Int

    public init(crawls: [CrawlResponse], page: Int, pageSize: Int, total: Int64, totalPages: Int) {
        self.crawls = crawls
        self.page = page
        self.pageSize = pageSize
        self.total = total
        self.totalPages = totalPages
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case crawls
        case page
        case pageSize
        case total
        case totalPages
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(crawls, forKey: .crawls)
        try container.encode(page, forKey: .page)
        try container.encode(pageSize, forKey: .pageSize)
        try container.encode(total, forKey: .total)
        try container.encode(totalPages, forKey: .totalPages)
    }
}

