//
// CrawlPageOutputResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct CrawlPageOutputResponse: Sendable, Codable, Hashable {

    public var contentType: String
    public var expiresAt: Date
    public var resultUrl: String
    public var size: Int64
    public var type: String

    public init(contentType: String, expiresAt: Date, resultUrl: String, size: Int64, type: String) {
        self.contentType = contentType
        self.expiresAt = expiresAt
        self.resultUrl = resultUrl
        self.size = size
        self.type = type
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case contentType
        case expiresAt
        case resultUrl
        case size
        case type
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(contentType, forKey: .contentType)
        try container.encode(expiresAt, forKey: .expiresAt)
        try container.encode(resultUrl, forKey: .resultUrl)
        try container.encode(size, forKey: .size)
        try container.encode(type, forKey: .type)
    }
}

