//
// CrawlResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct CrawlResponse: Sendable, Codable, Hashable {

    public enum Status: String, Sendable, Codable, CaseIterable {
        case queued = "QUEUED"
        case running = "RUNNING"
        case completed = "COMPLETED"
        case partiallyCompleted = "PARTIALLY_COMPLETED"
        case failed = "FAILED"
        case cancelled = "CANCELLED"
    }
    public static let outputsRule = ArrayRule(minItems: nil, maxItems: nil, uniqueItems: true)
    public var completedAt: Date?
    public var createdAt: Date
    public var depth: Int
    public var errorCode: String?
    public var errorMessage: String?
    public var id: String
    public var limit: Int
    public var outputs: Set<OutputSpec>
    public var progress: CrawlProgressResponse
    public var startedAt: Date?
    public var status: Status
    public var url: String

    public init(completedAt: Date? = nil, createdAt: Date, depth: Int, errorCode: String? = nil, errorMessage: String? = nil, id: String, limit: Int, outputs: Set<OutputSpec>, progress: CrawlProgressResponse, startedAt: Date? = nil, status: Status, url: String) {
        self.completedAt = completedAt
        self.createdAt = createdAt
        self.depth = depth
        self.errorCode = errorCode
        self.errorMessage = errorMessage
        self.id = id
        self.limit = limit
        self.outputs = outputs
        self.progress = progress
        self.startedAt = startedAt
        self.status = status
        self.url = url
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case completedAt
        case createdAt
        case depth
        case errorCode
        case errorMessage
        case id
        case limit
        case outputs
        case progress
        case startedAt
        case status
        case url
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(completedAt, forKey: .completedAt)
        try container.encode(createdAt, forKey: .createdAt)
        try container.encode(depth, forKey: .depth)
        try container.encodeIfPresent(errorCode, forKey: .errorCode)
        try container.encodeIfPresent(errorMessage, forKey: .errorMessage)
        try container.encode(id, forKey: .id)
        try container.encode(limit, forKey: .limit)
        try container.encode(outputs, forKey: .outputs)
        try container.encode(progress, forKey: .progress)
        try container.encodeIfPresent(startedAt, forKey: .startedAt)
        try container.encode(status, forKey: .status)
        try container.encode(url, forKey: .url)
    }
}

