//
// CrawlProgressResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct CrawlProgressResponse: Sendable, Codable, Hashable {

    public var charged: Int
    public var completed: Int
    public var discovered: Int
    public var failed: Int
    public var queued: Int
    public var skipped: Int

    public init(charged: Int, completed: Int, discovered: Int, failed: Int, queued: Int, skipped: Int) {
        self.charged = charged
        self.completed = completed
        self.discovered = discovered
        self.failed = failed
        self.queued = queued
        self.skipped = skipped
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case charged
        case completed
        case discovered
        case failed
        case queued
        case skipped
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(charged, forKey: .charged)
        try container.encode(completed, forKey: .completed)
        try container.encode(discovered, forKey: .discovered)
        try container.encode(failed, forKey: .failed)
        try container.encode(queued, forKey: .queued)
        try container.encode(skipped, forKey: .skipped)
    }
}

