//
// CreditBalanceResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct CreditBalanceResponse: Sendable, Codable, Hashable {

    public var allowanceType: String
    public var balance: Int
    public var resetsAt: String?

    public init(allowanceType: String, balance: Int, resetsAt: String? = nil) {
        self.allowanceType = allowanceType
        self.balance = balance
        self.resetsAt = resetsAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case allowanceType
        case balance
        case resetsAt
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(allowanceType, forKey: .allowanceType)
        try container.encode(balance, forKey: .balance)
        try container.encodeIfPresent(resetsAt, forKey: .resetsAt)
    }
}

