//
// DailyCaptureCountResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct DailyCaptureCountResponse: Sendable, Codable, Hashable {

    public var count: Int64
    public var date: String

    public init(count: Int64, date: String) {
        self.count = count
        self.date = date
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case count
        case date
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(count, forKey: .count)
        try container.encode(date, forKey: .date)
    }
}

