//
// DeliveryDestination.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public enum DeliveryDestination: Sendable, Codable, Hashable {
    case typeEmailDestination(EmailDestination)
    case typeWebhookDestination(WebhookDestination)

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .typeEmailDestination(let value):
            try container.encode(value)
        case .typeWebhookDestination(let value):
            try container.encode(value)
        }
    }

    private enum DiscriminatorCodingKey: String, CodingKey {
        case type = "type"
    }

    public init(from decoder: Decoder) throws {
        let keyedContainer = try decoder.container(keyedBy: DiscriminatorCodingKey.self)
        let discriminatorValue = try keyedContainer.decode(String.self, forKey: .type)

        switch discriminatorValue {
        case "email":
            self = .typeEmailDestination(try EmailDestination(from: decoder))
        case "webhook":
            self = .typeWebhookDestination(try WebhookDestination(from: decoder))
        default:
            throw DecodingError.dataCorrupted(
                DecodingError.Context(
                    codingPath: decoder.codingPath,
                    debugDescription: "Unknown discriminator value '\(discriminatorValue)' for DeliveryDestination"
                )
            )
        }
    }
}

