//
// EmailDestination.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct EmailDestination: Sendable, Codable, Hashable {

    public enum ModelType: String, Sendable, Codable, CaseIterable {
        case email = "email"
    }
    public var id: String?
    public var onlyOnChange: Bool?
    public var subject: String?
    public var to: [String]
    public var type: ModelType

    public init(id: String? = nil, onlyOnChange: Bool? = nil, subject: String? = nil, to: [String], type: ModelType) {
        self.id = id
        self.onlyOnChange = onlyOnChange
        self.subject = subject
        self.to = to
        self.type = type
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case onlyOnChange
        case subject
        case to
        case type
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(onlyOnChange, forKey: .onlyOnChange)
        try container.encodeIfPresent(subject, forKey: .subject)
        try container.encode(to, forKey: .to)
        try container.encode(type, forKey: .type)
    }
}

