//
// ErrorDetail.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ErrorDetail: Sendable, Codable, Hashable {

    public var code: String
    public var details: [String: JSONValue]?
    public var documentationUrl: String?
    public var message: String

    public init(code: String, details: [String: JSONValue]? = nil, documentationUrl: String? = nil, message: String) {
        self.code = code
        self.details = details
        self.documentationUrl = documentationUrl
        self.message = message
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case code
        case details
        case documentationUrl
        case message
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(code, forKey: .code)
        try container.encodeIfPresent(details, forKey: .details)
        try container.encodeIfPresent(documentationUrl, forKey: .documentationUrl)
        try container.encode(message, forKey: .message)
    }
}

