//
// HoverAction.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct HoverAction: Sendable, Codable, Hashable {

    public enum ModelType: String, Sendable, Codable, CaseIterable {
        case hover = "hover"
    }
    public var _optional: Bool? = false
    public var selector: String
    public var timeout: Int?
    public var type: ModelType

    public init(_optional: Bool? = false, selector: String, timeout: Int? = nil, type: ModelType) {
        self._optional = _optional
        self.selector = selector
        self.timeout = timeout
        self.type = type
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case _optional = "optional"
        case selector
        case timeout
        case type
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(_optional, forKey: ._optional)
        try container.encode(selector, forKey: .selector)
        try container.encodeIfPresent(timeout, forKey: .timeout)
        try container.encode(type, forKey: .type)
    }
}

