//
// JobResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct JobResponse: Sendable, Codable, Hashable {

    public enum Status: String, Sendable, Codable, CaseIterable {
        case queued = "QUEUED"
        case processing = "PROCESSING"
        case completed = "COMPLETED"
        case failed = "FAILED"
        case cancelled = "CANCELLED"
    }
    public var completedAt: Date?
    public var createdAt: Date
    public var errorCode: String?
    public var errorMessage: String?
    public var expiresAt: Date?
    public var id: String
    public var metadata: [String: JSONValue]?
    public var outputs: [String: OutputInfo]?
    public var resultUrl: String?
    public var startedAt: Date?
    public var status: Status
    public var storageUrl: String?
    public var url: String

    public init(completedAt: Date? = nil, createdAt: Date, errorCode: String? = nil, errorMessage: String? = nil, expiresAt: Date? = nil, id: String, metadata: [String: JSONValue]? = nil, outputs: [String: OutputInfo]? = nil, resultUrl: String? = nil, startedAt: Date? = nil, status: Status, storageUrl: String? = nil, url: String) {
        self.completedAt = completedAt
        self.createdAt = createdAt
        self.errorCode = errorCode
        self.errorMessage = errorMessage
        self.expiresAt = expiresAt
        self.id = id
        self.metadata = metadata
        self.outputs = outputs
        self.resultUrl = resultUrl
        self.startedAt = startedAt
        self.status = status
        self.storageUrl = storageUrl
        self.url = url
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case completedAt
        case createdAt
        case errorCode
        case errorMessage
        case expiresAt
        case id
        case metadata
        case outputs
        case resultUrl
        case startedAt
        case status
        case storageUrl
        case url
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(completedAt, forKey: .completedAt)
        try container.encode(createdAt, forKey: .createdAt)
        try container.encodeIfPresent(errorCode, forKey: .errorCode)
        try container.encodeIfPresent(errorMessage, forKey: .errorMessage)
        try container.encodeIfPresent(expiresAt, forKey: .expiresAt)
        try container.encode(id, forKey: .id)
        try container.encodeIfPresent(metadata, forKey: .metadata)
        try container.encodeIfPresent(outputs, forKey: .outputs)
        try container.encodeIfPresent(resultUrl, forKey: .resultUrl)
        try container.encodeIfPresent(startedAt, forKey: .startedAt)
        try container.encode(status, forKey: .status)
        try container.encodeIfPresent(storageUrl, forKey: .storageUrl)
        try container.encode(url, forKey: .url)
    }
}

