//
// JsonFieldSpec.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct JsonFieldSpec: Sendable, Codable, Hashable {

    public var attribute: String?
    public var multiple: Bool? = false
    public var selector: String
    public var type: String? = "text"

    public init(attribute: String? = nil, multiple: Bool? = false, selector: String, type: String? = "text") {
        self.attribute = attribute
        self.multiple = multiple
        self.selector = selector
        self.type = type
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case attribute
        case multiple
        case selector
        case type
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(attribute, forKey: .attribute)
        try container.encodeIfPresent(multiple, forKey: .multiple)
        try container.encode(selector, forKey: .selector)
        try container.encodeIfPresent(type, forKey: .type)
    }
}

