//
// JsonOutputSpec.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct JsonOutputSpec: Sendable, Codable, Hashable {

    public enum ModelType: String, Sendable, Codable, CaseIterable {
        case json = "json"
    }
    public var id: String?
    public var schema: [String: JsonFieldSpec]
    public var type: ModelType

    public init(id: String? = nil, schema: [String: JsonFieldSpec], type: ModelType) {
        self.id = id
        self.schema = schema
        self.type = type
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case schema
        case type
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encode(schema, forKey: .schema)
        try container.encode(type, forKey: .type)
    }
}

