//
// LabelConfig.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct LabelConfig: Sendable, Codable, Hashable {

    public static let fontSizeRule = NumericRule<Int>(minimum: 8, exclusiveMinimum: false, maximum: 48, exclusiveMaximum: false, multipleOf: nil)
    public static let paddingRule = NumericRule<Int>(minimum: 0, exclusiveMinimum: false, maximum: 20, exclusiveMaximum: false, multipleOf: nil)
    public static let positionRule = StringRule(minLength: nil, maxLength: nil, pattern: "^(top|bottom)$")
    public var background: String? = "#ffffff"
    public var fontColor: String? = "#333333"
    public var fontSize: Int? = 14
    public var padding: Int? = 8
    public var position: String? = "bottom"
    public var show: Bool? = true

    public init(background: String? = "#ffffff", fontColor: String? = "#333333", fontSize: Int? = 14, padding: Int? = 8, position: String? = "bottom", show: Bool? = true) {
        self.background = background
        self.fontColor = fontColor
        self.fontSize = fontSize
        self.padding = padding
        self.position = position
        self.show = show
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case background
        case fontColor
        case fontSize
        case padding
        case position
        case show
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(background, forKey: .background)
        try container.encodeIfPresent(fontColor, forKey: .fontColor)
        try container.encodeIfPresent(fontSize, forKey: .fontSize)
        try container.encodeIfPresent(padding, forKey: .padding)
        try container.encodeIfPresent(position, forKey: .position)
        try container.encodeIfPresent(show, forKey: .show)
    }
}

