//
// LayoutPreviewResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct LayoutPreviewResponse: Sendable, Codable, Hashable {

    public var canvasHeight: Int
    public var canvasWidth: Int
    public var layout: String
    public var metadata: [String: JSONValue]
    public var placements: [PlacementPreview]
    public var resolvedLayout: String

    public init(canvasHeight: Int, canvasWidth: Int, layout: String, metadata: [String: JSONValue], placements: [PlacementPreview], resolvedLayout: String) {
        self.canvasHeight = canvasHeight
        self.canvasWidth = canvasWidth
        self.layout = layout
        self.metadata = metadata
        self.placements = placements
        self.resolvedLayout = resolvedLayout
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case canvasHeight
        case canvasWidth
        case layout
        case metadata
        case placements
        case resolvedLayout
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(canvasHeight, forKey: .canvasHeight)
        try container.encode(canvasWidth, forKey: .canvasWidth)
        try container.encode(layout, forKey: .layout)
        try container.encode(metadata, forKey: .metadata)
        try container.encode(placements, forKey: .placements)
        try container.encode(resolvedLayout, forKey: .resolvedLayout)
    }
}

