//
// MarkdownOutputSpec.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct MarkdownOutputSpec: Sendable, Codable, Hashable {

    public enum ModelType: String, Sendable, Codable, CaseIterable {
        case markdown = "markdown"
    }
    public var id: String?
    public var mainContentOnly: Bool? = true
    public var type: ModelType

    public init(id: String? = nil, mainContentOnly: Bool? = true, type: ModelType) {
        self.id = id
        self.mainContentOnly = mainContentOnly
        self.type = type
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case mainContentOnly
        case type
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(mainContentOnly, forKey: .mainContentOnly)
        try container.encode(type, forKey: .type)
    }
}

