//
// ModelErrorResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ModelErrorResponse: Sendable, Codable, Hashable {

    public var error: ErrorDetail
    public var requestId: String?

    public init(error: ErrorDetail, requestId: String? = nil) {
        self.error = error
        self.requestId = requestId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case error
        case requestId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(error, forKey: .error)
        try container.encodeIfPresent(requestId, forKey: .requestId)
    }
}

