//
// MultiOutputResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct MultiOutputResponse: Sendable, Codable, Hashable {

    public var outputs: [String: JSONValue]
    public var renderTimeMs: Int64
    public var url: String

    public init(outputs: [String: JSONValue], renderTimeMs: Int64, url: String) {
        self.outputs = outputs
        self.renderTimeMs = renderTimeMs
        self.url = url
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case outputs
        case renderTimeMs
        case url
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(outputs, forKey: .outputs)
        try container.encode(renderTimeMs, forKey: .renderTimeMs)
        try container.encode(url, forKey: .url)
    }
}

