//
// OutputSpec.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public enum OutputSpec: Sendable, Codable, Hashable {
    case typeHtmlOutputSpec(HtmlOutputSpec)
    case typeJsonOutputSpec(JsonOutputSpec)
    case typeMarkdownOutputSpec(MarkdownOutputSpec)
    case typePdfOutputSpec(PdfOutputSpec)
    case typeScreenshotOutputSpec(ScreenshotOutputSpec)

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .typeHtmlOutputSpec(let value):
            try container.encode(value)
        case .typeJsonOutputSpec(let value):
            try container.encode(value)
        case .typeMarkdownOutputSpec(let value):
            try container.encode(value)
        case .typePdfOutputSpec(let value):
            try container.encode(value)
        case .typeScreenshotOutputSpec(let value):
            try container.encode(value)
        }
    }

    private enum DiscriminatorCodingKey: String, CodingKey {
        case type = "type"
    }

    public init(from decoder: Decoder) throws {
        let keyedContainer = try decoder.container(keyedBy: DiscriminatorCodingKey.self)
        let discriminatorValue = try keyedContainer.decode(String.self, forKey: .type)

        switch discriminatorValue {
        case "html":
            self = .typeHtmlOutputSpec(try HtmlOutputSpec(from: decoder))
        case "json":
            self = .typeJsonOutputSpec(try JsonOutputSpec(from: decoder))
        case "markdown":
            self = .typeMarkdownOutputSpec(try MarkdownOutputSpec(from: decoder))
        case "pdf":
            self = .typePdfOutputSpec(try PdfOutputSpec(from: decoder))
        case "screenshot":
            self = .typeScreenshotOutputSpec(try ScreenshotOutputSpec(from: decoder))
        default:
            throw DecodingError.dataCorrupted(
                DecodingError.Context(
                    codingPath: decoder.codingPath,
                    debugDescription: "Unknown discriminator value '\(discriminatorValue)' for OutputSpec"
                )
            )
        }
    }
}

