//
// OutputInfo.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct OutputInfo: Sendable, Codable, Hashable {

    public var contentType: String
    public var resultUrl: String?
    public var size: Int64
    public var storageUrl: String?
    public var type: String

    public init(contentType: String, resultUrl: String? = nil, size: Int64, storageUrl: String? = nil, type: String) {
        self.contentType = contentType
        self.resultUrl = resultUrl
        self.size = size
        self.storageUrl = storageUrl
        self.type = type
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case contentType
        case resultUrl
        case size
        case storageUrl
        case type
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(contentType, forKey: .contentType)
        try container.encodeIfPresent(resultUrl, forKey: .resultUrl)
        try container.encode(size, forKey: .size)
        try container.encodeIfPresent(storageUrl, forKey: .storageUrl)
        try container.encode(type, forKey: .type)
    }
}

