//
// PageAction.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public enum PageAction: Sendable, Codable, Hashable {
    case typeClickAction(ClickAction)
    case typeHoverAction(HoverAction)
    case typePressAction(PressAction)
    case typeScrollAction(ScrollAction)
    case typeSelectAction(SelectAction)
    case typeTypeAction(TypeAction)
    case typeWaitAction(WaitAction)

    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .typeClickAction(let value):
            try container.encode(value)
        case .typeHoverAction(let value):
            try container.encode(value)
        case .typePressAction(let value):
            try container.encode(value)
        case .typeScrollAction(let value):
            try container.encode(value)
        case .typeSelectAction(let value):
            try container.encode(value)
        case .typeTypeAction(let value):
            try container.encode(value)
        case .typeWaitAction(let value):
            try container.encode(value)
        }
    }

    private enum DiscriminatorCodingKey: String, CodingKey {
        case type = "type"
    }

    public init(from decoder: Decoder) throws {
        let keyedContainer = try decoder.container(keyedBy: DiscriminatorCodingKey.self)
        let discriminatorValue = try keyedContainer.decode(String.self, forKey: .type)

        switch discriminatorValue {
        case "click":
            self = .typeClickAction(try ClickAction(from: decoder))
        case "hover":
            self = .typeHoverAction(try HoverAction(from: decoder))
        case "press":
            self = .typePressAction(try PressAction(from: decoder))
        case "scroll":
            self = .typeScrollAction(try ScrollAction(from: decoder))
        case "select":
            self = .typeSelectAction(try SelectAction(from: decoder))
        case "type":
            self = .typeTypeAction(try TypeAction(from: decoder))
        case "wait":
            self = .typeWaitAction(try WaitAction(from: decoder))
        default:
            throw DecodingError.dataCorrupted(
                DecodingError.Context(
                    codingPath: decoder.codingPath,
                    debugDescription: "Unknown discriminator value '\(discriminatorValue)' for PageAction"
                )
            )
        }
    }
}

