//
// PdfOutputSpec.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct PdfOutputSpec: Sendable, Codable, Hashable {

    public enum ModelType: String, Sendable, Codable, CaseIterable {
        case pdf = "pdf"
    }
    public var format: String?
    public var id: String?
    public var landscape: Bool? = false
    public var printBackground: Bool? = true
    public var type: ModelType

    public init(format: String? = nil, id: String? = nil, landscape: Bool? = false, printBackground: Bool? = true, type: ModelType) {
        self.format = format
        self.id = id
        self.landscape = landscape
        self.printBackground = printBackground
        self.type = type
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case format
        case id
        case landscape
        case printBackground
        case type
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(format, forKey: .format)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(landscape, forKey: .landscape)
        try container.encodeIfPresent(printBackground, forKey: .printBackground)
        try container.encode(type, forKey: .type)
    }
}

