//
// PeriodUsageResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct PeriodUsageResponse: Sendable, Codable, Hashable {

    public var bandwidthBytes: Int64
    public var bandwidthFormatted: String
    public var periodEnd: String
    public var periodStart: String
    public var screenshotsCount: Int

    public init(bandwidthBytes: Int64, bandwidthFormatted: String, periodEnd: String, periodStart: String, screenshotsCount: Int) {
        self.bandwidthBytes = bandwidthBytes
        self.bandwidthFormatted = bandwidthFormatted
        self.periodEnd = periodEnd
        self.periodStart = periodStart
        self.screenshotsCount = screenshotsCount
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case bandwidthBytes
        case bandwidthFormatted
        case periodEnd
        case periodStart
        case screenshotsCount
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(bandwidthBytes, forKey: .bandwidthBytes)
        try container.encode(bandwidthFormatted, forKey: .bandwidthFormatted)
        try container.encode(periodEnd, forKey: .periodEnd)
        try container.encode(periodStart, forKey: .periodStart)
        try container.encode(screenshotsCount, forKey: .screenshotsCount)
    }
}

