//
// PlacementPreview.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct PlacementPreview: Sendable, Codable, Hashable {

    public var height: Int
    public var index: Int
    public var label: String?
    public var width: Int
    public var x: Int
    public var y: Int

    public init(height: Int, index: Int, label: String? = nil, width: Int, x: Int, y: Int) {
        self.height = height
        self.index = index
        self.label = label
        self.width = width
        self.x = x
        self.y = y
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case height
        case index
        case label
        case width
        case x
        case y
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(height, forKey: .height)
        try container.encode(index, forKey: .index)
        try container.encodeIfPresent(label, forKey: .label)
        try container.encode(width, forKey: .width)
        try container.encode(x, forKey: .x)
        try container.encode(y, forKey: .y)
    }
}

