//
// PressAction.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct PressAction: Sendable, Codable, Hashable {

    public enum ModelType: String, Sendable, Codable, CaseIterable {
        case press = "press"
    }
    public var key: String
    public var _optional: Bool? = false
    public var selector: String?
    public var timeout: Int?
    public var type: ModelType

    public init(key: String, _optional: Bool? = false, selector: String? = nil, timeout: Int? = nil, type: ModelType) {
        self.key = key
        self._optional = _optional
        self.selector = selector
        self.timeout = timeout
        self.type = type
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case key
        case _optional = "optional"
        case selector
        case timeout
        case type
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(key, forKey: .key)
        try container.encodeIfPresent(_optional, forKey: ._optional)
        try container.encodeIfPresent(selector, forKey: .selector)
        try container.encodeIfPresent(timeout, forKey: .timeout)
        try container.encode(type, forKey: .type)
    }
}

