//
// QuotaResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct QuotaResponse: Sendable, Codable, Hashable {

    public var bandwidth: BandwidthQuotaResponse
    public var screenshots: QuotaDetailResponse

    public init(bandwidth: BandwidthQuotaResponse, screenshots: QuotaDetailResponse) {
        self.bandwidth = bandwidth
        self.screenshots = screenshots
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case bandwidth
        case screenshots
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(bandwidth, forKey: .bandwidth)
        try container.encode(screenshots, forKey: .screenshots)
    }
}

