//
// QuotaStatusResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct QuotaStatusResponse: Sendable, Codable, Hashable {

    public var bandwidth: BandwidthQuotaResponse
    public var periodEnds: String?
    public var screenshots: QuotaDetailResponse
    public var tier: String

    public init(bandwidth: BandwidthQuotaResponse, periodEnds: String? = nil, screenshots: QuotaDetailResponse, tier: String) {
        self.bandwidth = bandwidth
        self.periodEnds = periodEnds
        self.screenshots = screenshots
        self.tier = tier
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case bandwidth
        case periodEnds
        case screenshots
        case tier
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(bandwidth, forKey: .bandwidth)
        try container.encodeIfPresent(periodEnds, forKey: .periodEnds)
        try container.encode(screenshots, forKey: .screenshots)
        try container.encode(tier, forKey: .tier)
    }
}

