//
// QuotaDetailResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct QuotaDetailResponse: Sendable, Codable, Hashable {

    public var limit: Int
    public var percentUsed: Int
    public var remaining: Int
    public var used: Int

    public init(limit: Int, percentUsed: Int, remaining: Int, used: Int) {
        self.limit = limit
        self.percentUsed = percentUsed
        self.remaining = remaining
        self.used = used
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case limit
        case percentUsed
        case remaining
        case used
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(limit, forKey: .limit)
        try container.encode(percentUsed, forKey: .percentUsed)
        try container.encode(remaining, forKey: .remaining)
        try container.encode(used, forKey: .used)
    }
}

