//
// ScheduleHistoryResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ScheduleHistoryResponse: Sendable, Codable, Hashable {

    public var executions: [ScheduleExecutionResponse]
    public var scheduleId: String
    public var totalExecutions: Int64

    public init(executions: [ScheduleExecutionResponse], scheduleId: String, totalExecutions: Int64) {
        self.executions = executions
        self.scheduleId = scheduleId
        self.totalExecutions = totalExecutions
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case executions
        case scheduleId
        case totalExecutions
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(executions, forKey: .executions)
        try container.encode(scheduleId, forKey: .scheduleId)
        try container.encode(totalExecutions, forKey: .totalExecutions)
    }
}

