//
// ScheduleExecutionResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ScheduleExecutionResponse: Sendable, Codable, Hashable {

    public var changed: Bool?
    public var deliveries: [[String: JSONValue]]?
    public var diffScore: Double?
    public var errorCode: String?
    public var errorMessage: String?
    public var executedAt: Date
    public var expiresAt: Date?
    public var fileSize: Int64?
    public var id: String
    public var outputs: [String: JSONValue]?
    public var renderTimeMs: Int64?
    public var resultUrl: String?
    public var runId: String?
    public var status: String
    public var storageUrl: String?
    public var url: String?

    public init(changed: Bool? = nil, deliveries: [[String: JSONValue]]? = nil, diffScore: Double? = nil, errorCode: String? = nil, errorMessage: String? = nil, executedAt: Date, expiresAt: Date? = nil, fileSize: Int64? = nil, id: String, outputs: [String: JSONValue]? = nil, renderTimeMs: Int64? = nil, resultUrl: String? = nil, runId: String? = nil, status: String, storageUrl: String? = nil, url: String? = nil) {
        self.changed = changed
        self.deliveries = deliveries
        self.diffScore = diffScore
        self.errorCode = errorCode
        self.errorMessage = errorMessage
        self.executedAt = executedAt
        self.expiresAt = expiresAt
        self.fileSize = fileSize
        self.id = id
        self.outputs = outputs
        self.renderTimeMs = renderTimeMs
        self.resultUrl = resultUrl
        self.runId = runId
        self.status = status
        self.storageUrl = storageUrl
        self.url = url
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case changed
        case deliveries
        case diffScore
        case errorCode
        case errorMessage
        case executedAt
        case expiresAt
        case fileSize
        case id
        case outputs
        case renderTimeMs
        case resultUrl
        case runId
        case status
        case storageUrl
        case url
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(changed, forKey: .changed)
        try container.encodeIfPresent(deliveries, forKey: .deliveries)
        try container.encodeIfPresent(diffScore, forKey: .diffScore)
        try container.encodeIfPresent(errorCode, forKey: .errorCode)
        try container.encodeIfPresent(errorMessage, forKey: .errorMessage)
        try container.encode(executedAt, forKey: .executedAt)
        try container.encodeIfPresent(expiresAt, forKey: .expiresAt)
        try container.encodeIfPresent(fileSize, forKey: .fileSize)
        try container.encode(id, forKey: .id)
        try container.encodeIfPresent(outputs, forKey: .outputs)
        try container.encodeIfPresent(renderTimeMs, forKey: .renderTimeMs)
        try container.encodeIfPresent(resultUrl, forKey: .resultUrl)
        try container.encodeIfPresent(runId, forKey: .runId)
        try container.encode(status, forKey: .status)
        try container.encodeIfPresent(storageUrl, forKey: .storageUrl)
        try container.encodeIfPresent(url, forKey: .url)
    }
}

