//
// ScheduleResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ScheduleResponse: Sendable, Codable, Hashable {

    public var alertOnFailure: Bool
    public var autoPauseAfterFailures: Int?
    public var consecutiveFailures: Int
    public var createdAt: Date
    public var destinations: [DeliveryDestination]?
    public var diffThreshold: Double?
    public var endsAt: Date?
    public var executionCount: Int
    public var failureCount: Int
    public var id: String
    public var lastExecutedAt: Date?
    public var name: String
    public var nextExecutionAt: Date?
    public var onlyOnChange: Bool
    public var options: [String: JSONValue]?
    public var retentionDays: Int
    public var schedule: String
    public var scheduleDescription: String
    public var startsAt: Date?
    public var status: String
    public var successCount: Int
    public var timezone: String
    public var updatedAt: Date
    public var url: String
    public var webhookUrl: String?

    public init(alertOnFailure: Bool, autoPauseAfterFailures: Int? = nil, consecutiveFailures: Int, createdAt: Date, destinations: [DeliveryDestination]? = nil, diffThreshold: Double? = nil, endsAt: Date? = nil, executionCount: Int, failureCount: Int, id: String, lastExecutedAt: Date? = nil, name: String, nextExecutionAt: Date? = nil, onlyOnChange: Bool, options: [String: JSONValue]? = nil, retentionDays: Int, schedule: String, scheduleDescription: String, startsAt: Date? = nil, status: String, successCount: Int, timezone: String, updatedAt: Date, url: String, webhookUrl: String? = nil) {
        self.alertOnFailure = alertOnFailure
        self.autoPauseAfterFailures = autoPauseAfterFailures
        self.consecutiveFailures = consecutiveFailures
        self.createdAt = createdAt
        self.destinations = destinations
        self.diffThreshold = diffThreshold
        self.endsAt = endsAt
        self.executionCount = executionCount
        self.failureCount = failureCount
        self.id = id
        self.lastExecutedAt = lastExecutedAt
        self.name = name
        self.nextExecutionAt = nextExecutionAt
        self.onlyOnChange = onlyOnChange
        self.options = options
        self.retentionDays = retentionDays
        self.schedule = schedule
        self.scheduleDescription = scheduleDescription
        self.startsAt = startsAt
        self.status = status
        self.successCount = successCount
        self.timezone = timezone
        self.updatedAt = updatedAt
        self.url = url
        self.webhookUrl = webhookUrl
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case alertOnFailure
        case autoPauseAfterFailures
        case consecutiveFailures
        case createdAt
        case destinations
        case diffThreshold
        case endsAt
        case executionCount
        case failureCount
        case id
        case lastExecutedAt
        case name
        case nextExecutionAt
        case onlyOnChange
        case options
        case retentionDays
        case schedule
        case scheduleDescription
        case startsAt
        case status
        case successCount
        case timezone
        case updatedAt
        case url
        case webhookUrl
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(alertOnFailure, forKey: .alertOnFailure)
        try container.encodeIfPresent(autoPauseAfterFailures, forKey: .autoPauseAfterFailures)
        try container.encode(consecutiveFailures, forKey: .consecutiveFailures)
        try container.encode(createdAt, forKey: .createdAt)
        try container.encodeIfPresent(destinations, forKey: .destinations)
        try container.encodeIfPresent(diffThreshold, forKey: .diffThreshold)
        try container.encodeIfPresent(endsAt, forKey: .endsAt)
        try container.encode(executionCount, forKey: .executionCount)
        try container.encode(failureCount, forKey: .failureCount)
        try container.encode(id, forKey: .id)
        try container.encodeIfPresent(lastExecutedAt, forKey: .lastExecutedAt)
        try container.encode(name, forKey: .name)
        try container.encodeIfPresent(nextExecutionAt, forKey: .nextExecutionAt)
        try container.encode(onlyOnChange, forKey: .onlyOnChange)
        try container.encodeIfPresent(options, forKey: .options)
        try container.encode(retentionDays, forKey: .retentionDays)
        try container.encode(schedule, forKey: .schedule)
        try container.encode(scheduleDescription, forKey: .scheduleDescription)
        try container.encodeIfPresent(startsAt, forKey: .startsAt)
        try container.encode(status, forKey: .status)
        try container.encode(successCount, forKey: .successCount)
        try container.encode(timezone, forKey: .timezone)
        try container.encode(updatedAt, forKey: .updatedAt)
        try container.encode(url, forKey: .url)
        try container.encodeIfPresent(webhookUrl, forKey: .webhookUrl)
    }
}

