//
// ScheduleListResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ScheduleListResponse: Sendable, Codable, Hashable {

    public var schedules: [ScheduleResponse]
    public var total: Int

    public init(schedules: [ScheduleResponse], total: Int) {
        self.schedules = schedules
        self.total = total
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case schedules
        case total
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(schedules, forKey: .schedules)
        try container.encode(total, forKey: .total)
    }
}

