//
// ScreenshotOutputSpec.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ScreenshotOutputSpec: Sendable, Codable, Hashable {

    public enum ModelType: String, Sendable, Codable, CaseIterable {
        case screenshot = "screenshot"
    }
    public var format: String? = "png"
    public var fullPage: Bool? = false
    public var id: String?
    public var quality: Int? = 80
    public var selector: String?
    public var type: ModelType

    public init(format: String? = "png", fullPage: Bool? = false, id: String? = nil, quality: Int? = 80, selector: String? = nil, type: ModelType) {
        self.format = format
        self.fullPage = fullPage
        self.id = id
        self.quality = quality
        self.selector = selector
        self.type = type
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case format
        case fullPage
        case id
        case quality
        case selector
        case type
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(format, forKey: .format)
        try container.encodeIfPresent(fullPage, forKey: .fullPage)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(quality, forKey: .quality)
        try container.encodeIfPresent(selector, forKey: .selector)
        try container.encode(type, forKey: .type)
    }
}

