//
// ScreenshotRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ScreenshotRequest: Sendable, Codable, Hashable {

    public enum ResponseType: String, Sendable, Codable, CaseIterable {
        case binary = "BINARY"
        case base64 = "BASE64"
        case url = "URL"
    }
    public static let actionsRule = ArrayRule(minItems: 0, maxItems: 25, uniqueItems: false)
    public static let blockLevelRule = StringRule(minLength: nil, maxLength: nil, pattern: "^(none|light|normal|pro|pro_plus|ultimate)$")
    public static let customCssRule = StringRule(minLength: 0, maxLength: 10000, pattern: nil)
    public static let delayRule = NumericRule<Int>(minimum: 0, exclusiveMinimum: false, maximum: 30000, exclusiveMaximum: false, multipleOf: nil)
    public static let formatRule = StringRule(minLength: nil, maxLength: nil, pattern: "^(png|jpeg|jpg|webp|pdf)$")
    public static let fullPageModeRule = StringRule(minLength: nil, maxLength: nil, pattern: "^(native|stitch)$")
    public static let hideSelectorsRule = ArrayRule(minItems: 0, maxItems: 50, uniqueItems: false)
    public static let maxHeightRule = NumericRule<Int>(minimum: 1000, exclusiveMinimum: false, maximum: 30000, exclusiveMaximum: false, multipleOf: nil)
    public static let maxSectionsRule = NumericRule<Int>(minimum: 1, exclusiveMinimum: false, maximum: 50, exclusiveMaximum: false, multipleOf: nil)
    public static let qualityRule = NumericRule<Int>(minimum: 1, exclusiveMinimum: false, maximum: 100, exclusiveMaximum: false, multipleOf: nil)
    public static let scrollIntervalRule = NumericRule<Int>(minimum: 50, exclusiveMinimum: false, maximum: 1000, exclusiveMaximum: false, multipleOf: nil)
    public static let selectorRule = StringRule(minLength: 0, maxLength: 500, pattern: nil)
    public static let timeoutRule = NumericRule<Int>(minimum: 1000, exclusiveMinimum: false, maximum: 60000, exclusiveMaximum: false, multipleOf: nil)
    public static let urlRule = StringRule(minLength: 1, maxLength: nil, pattern: "^https?://.*")
    public static let waitUntilRule = StringRule(minLength: nil, maxLength: nil, pattern: "^(load|domcontentloaded|networkidle)$")
    public static let webhookSecretRule = StringRule(minLength: 0, maxLength: 255, pattern: nil)
    public static let webhookUrlRule = StringRule(minLength: nil, maxLength: nil, pattern: "^https?://.*")
    public var actions: [PageAction]?
    public var blockAds: Bool? = true
    public var blockCookieBanners: Bool? = true
    public var blockLevel: String? = "none"
    public var blockPopups: Bool? = true
    public var customCss: String?
    public var darkMode: Bool? = false
    public var delay: Int? = 0
    public var device: String?
    public var format: String? = "png"
    public var freezeFixed: Bool? = true
    public var fullPage: Bool? = false
    public var fullPageMode: String? = "stitch"
    public var hideSelectors: [String]?
    public var maxHeight: Int?
    public var maxSections: Int? = 50
    public var outputs: [OutputSpec]?
    public var quality: Int? = 80
    public var responseType: ResponseType? = .binary
    public var scrollInterval: Int? = 150
    public var selector: String?
    public var session: BrowserSessionRequest?
    public var stealthMode: Bool? = false
    public var timeout: Int? = 30000
    public var url: String
    public var viewport: ViewportConfig?
    public var waitFor: String?
    public var waitUntil: String? = "domcontentloaded"
    public var webhookSecret: String?
    public var webhookUrl: String?

    public init(actions: [PageAction]? = nil, blockAds: Bool? = true, blockCookieBanners: Bool? = true, blockLevel: String? = "none", blockPopups: Bool? = true, customCss: String? = nil, darkMode: Bool? = false, delay: Int? = 0, device: String? = nil, format: String? = "png", freezeFixed: Bool? = true, fullPage: Bool? = false, fullPageMode: String? = "stitch", hideSelectors: [String]? = nil, maxHeight: Int? = nil, maxSections: Int? = 50, outputs: [OutputSpec]? = nil, quality: Int? = 80, responseType: ResponseType? = .binary, scrollInterval: Int? = 150, selector: String? = nil, session: BrowserSessionRequest? = nil, stealthMode: Bool? = false, timeout: Int? = 30000, url: String, viewport: ViewportConfig? = nil, waitFor: String? = nil, waitUntil: String? = "domcontentloaded", webhookSecret: String? = nil, webhookUrl: String? = nil) {
        self.actions = actions
        self.blockAds = blockAds
        self.blockCookieBanners = blockCookieBanners
        self.blockLevel = blockLevel
        self.blockPopups = blockPopups
        self.customCss = customCss
        self.darkMode = darkMode
        self.delay = delay
        self.device = device
        self.format = format
        self.freezeFixed = freezeFixed
        self.fullPage = fullPage
        self.fullPageMode = fullPageMode
        self.hideSelectors = hideSelectors
        self.maxHeight = maxHeight
        self.maxSections = maxSections
        self.outputs = outputs
        self.quality = quality
        self.responseType = responseType
        self.scrollInterval = scrollInterval
        self.selector = selector
        self.session = session
        self.stealthMode = stealthMode
        self.timeout = timeout
        self.url = url
        self.viewport = viewport
        self.waitFor = waitFor
        self.waitUntil = waitUntil
        self.webhookSecret = webhookSecret
        self.webhookUrl = webhookUrl
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case actions
        case blockAds
        case blockCookieBanners
        case blockLevel
        case blockPopups
        case customCss
        case darkMode
        case delay
        case device
        case format
        case freezeFixed
        case fullPage
        case fullPageMode
        case hideSelectors
        case maxHeight
        case maxSections
        case outputs
        case quality
        case responseType
        case scrollInterval
        case selector
        case session
        case stealthMode
        case timeout
        case url
        case viewport
        case waitFor
        case waitUntil
        case webhookSecret
        case webhookUrl
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(actions, forKey: .actions)
        try container.encodeIfPresent(blockAds, forKey: .blockAds)
        try container.encodeIfPresent(blockCookieBanners, forKey: .blockCookieBanners)
        try container.encodeIfPresent(blockLevel, forKey: .blockLevel)
        try container.encodeIfPresent(blockPopups, forKey: .blockPopups)
        try container.encodeIfPresent(customCss, forKey: .customCss)
        try container.encodeIfPresent(darkMode, forKey: .darkMode)
        try container.encodeIfPresent(delay, forKey: .delay)
        try container.encodeIfPresent(device, forKey: .device)
        try container.encodeIfPresent(format, forKey: .format)
        try container.encodeIfPresent(freezeFixed, forKey: .freezeFixed)
        try container.encodeIfPresent(fullPage, forKey: .fullPage)
        try container.encodeIfPresent(fullPageMode, forKey: .fullPageMode)
        try container.encodeIfPresent(hideSelectors, forKey: .hideSelectors)
        try container.encodeIfPresent(maxHeight, forKey: .maxHeight)
        try container.encodeIfPresent(maxSections, forKey: .maxSections)
        try container.encodeIfPresent(outputs, forKey: .outputs)
        try container.encodeIfPresent(quality, forKey: .quality)
        try container.encodeIfPresent(responseType, forKey: .responseType)
        try container.encodeIfPresent(scrollInterval, forKey: .scrollInterval)
        try container.encodeIfPresent(selector, forKey: .selector)
        try container.encodeIfPresent(session, forKey: .session)
        try container.encodeIfPresent(stealthMode, forKey: .stealthMode)
        try container.encodeIfPresent(timeout, forKey: .timeout)
        try container.encode(url, forKey: .url)
        try container.encodeIfPresent(viewport, forKey: .viewport)
        try container.encodeIfPresent(waitFor, forKey: .waitFor)
        try container.encodeIfPresent(waitUntil, forKey: .waitUntil)
        try container.encodeIfPresent(webhookSecret, forKey: .webhookSecret)
        try container.encodeIfPresent(webhookUrl, forKey: .webhookUrl)
    }
}

