//
// ScreenshotJsonResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ScreenshotJsonResponse: Sendable, Codable, Hashable {

    public var cached: Bool? = false
    public var contentType: String
    public var data: String?
    public var encoding: String?
    public var expiresAt: Date?
    public var format: String
    public var height: Int?
    public var renderTimeMs: Int64
    public var resultUrl: String?
    public var size: Int
    public var storageUrl: String?
    public var url: String
    public var width: Int

    public init(cached: Bool? = false, contentType: String, data: String? = nil, encoding: String? = nil, expiresAt: Date? = nil, format: String, height: Int? = nil, renderTimeMs: Int64, resultUrl: String? = nil, size: Int, storageUrl: String? = nil, url: String, width: Int) {
        self.cached = cached
        self.contentType = contentType
        self.data = data
        self.encoding = encoding
        self.expiresAt = expiresAt
        self.format = format
        self.height = height
        self.renderTimeMs = renderTimeMs
        self.resultUrl = resultUrl
        self.size = size
        self.storageUrl = storageUrl
        self.url = url
        self.width = width
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case cached
        case contentType
        case data
        case encoding
        case expiresAt
        case format
        case height
        case renderTimeMs
        case resultUrl
        case size
        case storageUrl
        case url
        case width
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(cached, forKey: .cached)
        try container.encode(contentType, forKey: .contentType)
        try container.encodeIfPresent(data, forKey: .data)
        try container.encodeIfPresent(encoding, forKey: .encoding)
        try container.encodeIfPresent(expiresAt, forKey: .expiresAt)
        try container.encode(format, forKey: .format)
        try container.encodeIfPresent(height, forKey: .height)
        try container.encode(renderTimeMs, forKey: .renderTimeMs)
        try container.encodeIfPresent(resultUrl, forKey: .resultUrl)
        try container.encode(size, forKey: .size)
        try container.encodeIfPresent(storageUrl, forKey: .storageUrl)
        try container.encode(url, forKey: .url)
        try container.encode(width, forKey: .width)
    }
}

