//
// ScrollAction.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ScrollAction: Sendable, Codable, Hashable {

    public enum ModelType: String, Sendable, Codable, CaseIterable {
        case scroll = "scroll"
    }
    public var _optional: Bool? = false
    public var selector: String?
    public var timeout: Int?
    public var toBottom: Bool? = false
    public var type: ModelType
    public var y: Int?

    public init(_optional: Bool? = false, selector: String? = nil, timeout: Int? = nil, toBottom: Bool? = false, type: ModelType, y: Int? = nil) {
        self._optional = _optional
        self.selector = selector
        self.timeout = timeout
        self.toBottom = toBottom
        self.type = type
        self.y = y
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case _optional = "optional"
        case selector
        case timeout
        case toBottom
        case type
        case y
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(_optional, forKey: ._optional)
        try container.encodeIfPresent(selector, forKey: .selector)
        try container.encodeIfPresent(timeout, forKey: .timeout)
        try container.encodeIfPresent(toBottom, forKey: .toBottom)
        try container.encode(type, forKey: .type)
        try container.encodeIfPresent(y, forKey: .y)
    }
}

