//
// ShadowConfig.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ShadowConfig: Sendable, Codable, Hashable {

    public static let blurRule = NumericRule<Int>(minimum: 0, exclusiveMinimum: false, maximum: 50, exclusiveMaximum: false, multipleOf: nil)
    public static let offsetXRule = NumericRule<Int>(minimum: -20, exclusiveMinimum: false, maximum: 20, exclusiveMaximum: false, multipleOf: nil)
    public static let offsetYRule = NumericRule<Int>(minimum: -20, exclusiveMinimum: false, maximum: 20, exclusiveMaximum: false, multipleOf: nil)
    public var blur: Int? = 10
    public var color: String? = "rgba(0,0,0,0.2)"
    public var enabled: Bool? = true
    public var offsetX: Int? = 0
    public var offsetY: Int? = 4

    public init(blur: Int? = 10, color: String? = "rgba(0,0,0,0.2)", enabled: Bool? = true, offsetX: Int? = 0, offsetY: Int? = 4) {
        self.blur = blur
        self.color = color
        self.enabled = enabled
        self.offsetX = offsetX
        self.offsetY = offsetY
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case blur
        case color
        case enabled
        case offsetX
        case offsetY
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(blur, forKey: .blur)
        try container.encodeIfPresent(color, forKey: .color)
        try container.encodeIfPresent(enabled, forKey: .enabled)
        try container.encodeIfPresent(offsetX, forKey: .offsetX)
        try container.encodeIfPresent(offsetY, forKey: .offsetY)
    }
}

