//
// TotalsResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct TotalsResponse: Sendable, Codable, Hashable {

    public var bandwidthBytes: Int64
    public var bandwidthFormatted: String
    public var screenshotsCount: Int64

    public init(bandwidthBytes: Int64, bandwidthFormatted: String, screenshotsCount: Int64) {
        self.bandwidthBytes = bandwidthBytes
        self.bandwidthFormatted = bandwidthFormatted
        self.screenshotsCount = screenshotsCount
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case bandwidthBytes
        case bandwidthFormatted
        case screenshotsCount
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(bandwidthBytes, forKey: .bandwidthBytes)
        try container.encode(bandwidthFormatted, forKey: .bandwidthFormatted)
        try container.encode(screenshotsCount, forKey: .screenshotsCount)
    }
}

