//
// TypeAction.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct TypeAction: Sendable, Codable, Hashable {

    public enum ModelType: String, Sendable, Codable, CaseIterable {
        case type = "type"
    }
    public var clear: Bool? = true
    public var _optional: Bool? = false
    public var selector: String
    public var text: String
    public var timeout: Int?
    public var type: ModelType

    public init(clear: Bool? = true, _optional: Bool? = false, selector: String, text: String, timeout: Int? = nil, type: ModelType) {
        self.clear = clear
        self._optional = _optional
        self.selector = selector
        self.text = text
        self.timeout = timeout
        self.type = type
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case clear
        case _optional = "optional"
        case selector
        case text
        case timeout
        case type
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(clear, forKey: .clear)
        try container.encodeIfPresent(_optional, forKey: ._optional)
        try container.encode(selector, forKey: .selector)
        try container.encode(text, forKey: .text)
        try container.encodeIfPresent(timeout, forKey: .timeout)
        try container.encode(type, forKey: .type)
    }
}

