//
// UpdateScheduleRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct UpdateScheduleRequest: Sendable, Codable, Hashable {

    public static let autoPauseAfterFailuresRule = NumericRule<Int>(minimum: 1, exclusiveMinimum: false, maximum: 100, exclusiveMaximum: false, multipleOf: nil)
    public static let destinationsRule = ArrayRule(minItems: 0, maxItems: 10, uniqueItems: false)
    public static let diffThresholdRule = NumericRule<Double>(minimum: 0.0, exclusiveMinimum: false, maximum: 1.0, exclusiveMaximum: false, multipleOf: nil)
    public static let nameRule = StringRule(minLength: 0, maxLength: 255, pattern: nil)
    public static let retentionDaysRule = NumericRule<Int>(minimum: 1, exclusiveMinimum: false, maximum: 365, exclusiveMaximum: false, multipleOf: nil)
    public var alertOnFailure: Bool?
    public var autoPauseAfterFailures: Int?
    public var destinations: [DeliveryDestination]?
    public var diffThreshold: Double?
    public var endsAt: Date?
    public var name: String?
    public var onlyOnChange: Bool?
    public var options: ScheduleScreenshotOptions?
    public var retentionDays: Int?
    public var schedule: String?
    public var startsAt: Date?
    public var timezone: String?
    public var url: String?
    public var webhookSecret: String?
    public var webhookUrl: String?

    public init(alertOnFailure: Bool? = nil, autoPauseAfterFailures: Int? = nil, destinations: [DeliveryDestination]? = nil, diffThreshold: Double? = nil, endsAt: Date? = nil, name: String? = nil, onlyOnChange: Bool? = nil, options: ScheduleScreenshotOptions? = nil, retentionDays: Int? = nil, schedule: String? = nil, startsAt: Date? = nil, timezone: String? = nil, url: String? = nil, webhookSecret: String? = nil, webhookUrl: String? = nil) {
        self.alertOnFailure = alertOnFailure
        self.autoPauseAfterFailures = autoPauseAfterFailures
        self.destinations = destinations
        self.diffThreshold = diffThreshold
        self.endsAt = endsAt
        self.name = name
        self.onlyOnChange = onlyOnChange
        self.options = options
        self.retentionDays = retentionDays
        self.schedule = schedule
        self.startsAt = startsAt
        self.timezone = timezone
        self.url = url
        self.webhookSecret = webhookSecret
        self.webhookUrl = webhookUrl
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case alertOnFailure
        case autoPauseAfterFailures
        case destinations
        case diffThreshold
        case endsAt
        case name
        case onlyOnChange
        case options
        case retentionDays
        case schedule
        case startsAt
        case timezone
        case url
        case webhookSecret
        case webhookUrl
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(alertOnFailure, forKey: .alertOnFailure)
        try container.encodeIfPresent(autoPauseAfterFailures, forKey: .autoPauseAfterFailures)
        try container.encodeIfPresent(destinations, forKey: .destinations)
        try container.encodeIfPresent(diffThreshold, forKey: .diffThreshold)
        try container.encodeIfPresent(endsAt, forKey: .endsAt)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(onlyOnChange, forKey: .onlyOnChange)
        try container.encodeIfPresent(options, forKey: .options)
        try container.encodeIfPresent(retentionDays, forKey: .retentionDays)
        try container.encodeIfPresent(schedule, forKey: .schedule)
        try container.encodeIfPresent(startsAt, forKey: .startsAt)
        try container.encodeIfPresent(timezone, forKey: .timezone)
        try container.encodeIfPresent(url, forKey: .url)
        try container.encodeIfPresent(webhookSecret, forKey: .webhookSecret)
        try container.encodeIfPresent(webhookUrl, forKey: .webhookUrl)
    }
}

