//
// UsageResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct UsageResponse: Sendable, Codable, Hashable {

    public var credits: CreditBalanceResponse
    public var currentPeriod: PeriodUsageResponse
    public var history: [PeriodUsageResponse]
    public var organization: UsageOrganizationResponse
    public var quota: QuotaResponse
    public var tier: String
    public var totals: TotalsResponse

    public init(credits: CreditBalanceResponse, currentPeriod: PeriodUsageResponse, history: [PeriodUsageResponse], organization: UsageOrganizationResponse, quota: QuotaResponse, tier: String, totals: TotalsResponse) {
        self.credits = credits
        self.currentPeriod = currentPeriod
        self.history = history
        self.organization = organization
        self.quota = quota
        self.tier = tier
        self.totals = totals
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case credits
        case currentPeriod
        case history
        case organization
        case quota
        case tier
        case totals
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(credits, forKey: .credits)
        try container.encode(currentPeriod, forKey: .currentPeriod)
        try container.encode(history, forKey: .history)
        try container.encode(organization, forKey: .organization)
        try container.encode(quota, forKey: .quota)
        try container.encode(tier, forKey: .tier)
        try container.encode(totals, forKey: .totals)
    }
}

