//
// VariantConfig.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct VariantConfig: Sendable, Codable, Hashable {

    public var customCss: String?
    public var darkMode: Bool?
    public var delay: Int?
    public var device: String?
    public var fullPage: Bool?
    public var id: String?
    public var label: String?
    public var viewport: ViewportConfig?

    public init(customCss: String? = nil, darkMode: Bool? = nil, delay: Int? = nil, device: String? = nil, fullPage: Bool? = nil, id: String? = nil, label: String? = nil, viewport: ViewportConfig? = nil) {
        self.customCss = customCss
        self.darkMode = darkMode
        self.delay = delay
        self.device = device
        self.fullPage = fullPage
        self.id = id
        self.label = label
        self.viewport = viewport
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case customCss
        case darkMode
        case delay
        case device
        case fullPage
        case id
        case label
        case viewport
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(customCss, forKey: .customCss)
        try container.encodeIfPresent(darkMode, forKey: .darkMode)
        try container.encodeIfPresent(delay, forKey: .delay)
        try container.encodeIfPresent(device, forKey: .device)
        try container.encodeIfPresent(fullPage, forKey: .fullPage)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(label, forKey: .label)
        try container.encodeIfPresent(viewport, forKey: .viewport)
    }
}

