//
// ViewportConfig.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ViewportConfig: Sendable, Codable, Hashable {

    public static let deviceScaleFactorRule = NumericRule<Int>(minimum: 1, exclusiveMinimum: false, maximum: 3, exclusiveMaximum: false, multipleOf: nil)
    public static let heightRule = NumericRule<Int>(minimum: 100, exclusiveMinimum: false, maximum: 2160, exclusiveMaximum: false, multipleOf: nil)
    public static let widthRule = NumericRule<Int>(minimum: 100, exclusiveMinimum: false, maximum: 2560, exclusiveMaximum: false, multipleOf: nil)
    public var deviceScaleFactor: Int? = 1
    public var height: Int? = 1080
    public var width: Int? = 1920

    public init(deviceScaleFactor: Int? = 1, height: Int? = 1080, width: Int? = 1920) {
        self.deviceScaleFactor = deviceScaleFactor
        self.height = height
        self.width = width
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case deviceScaleFactor
        case height
        case width
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(deviceScaleFactor, forKey: .deviceScaleFactor)
        try container.encodeIfPresent(height, forKey: .height)
        try container.encodeIfPresent(width, forKey: .width)
    }
}

