//
// WaitAction.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct WaitAction: Sendable, Codable, Hashable {

    public enum ModelType: String, Sendable, Codable, CaseIterable {
        case wait = "wait"
    }
    public var ms: Int?
    public var networkIdle: Bool? = false
    public var _optional: Bool? = false
    public var selector: String?
    public var timeout: Int?
    public var type: ModelType

    public init(ms: Int? = nil, networkIdle: Bool? = false, _optional: Bool? = false, selector: String? = nil, timeout: Int? = nil, type: ModelType) {
        self.ms = ms
        self.networkIdle = networkIdle
        self._optional = _optional
        self.selector = selector
        self.timeout = timeout
        self.type = type
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case ms
        case networkIdle
        case _optional = "optional"
        case selector
        case timeout
        case type
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(ms, forKey: .ms)
        try container.encodeIfPresent(networkIdle, forKey: .networkIdle)
        try container.encodeIfPresent(_optional, forKey: ._optional)
        try container.encodeIfPresent(selector, forKey: .selector)
        try container.encodeIfPresent(timeout, forKey: .timeout)
        try container.encode(type, forKey: .type)
    }
}

