//
// WebhookDestination.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct WebhookDestination: Sendable, Codable, Hashable {

    public enum ModelType: String, Sendable, Codable, CaseIterable {
        case webhook = "webhook"
    }
    public var id: String?
    public var onlyOnChange: Bool?
    public var secret: String?
    public var type: ModelType
    public var url: String

    public init(id: String? = nil, onlyOnChange: Bool? = nil, secret: String? = nil, type: ModelType, url: String) {
        self.id = id
        self.onlyOnChange = onlyOnChange
        self.secret = secret
        self.type = type
        self.url = url
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case onlyOnChange
        case secret
        case type
        case url
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(onlyOnChange, forKey: .onlyOnChange)
        try container.encodeIfPresent(secret, forKey: .secret)
        try container.encode(type, forKey: .type)
        try container.encode(url, forKey: .url)
    }
}

