//
// ComposeAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

open class ComposeAPI {

    /**

     - parameter composeRequest: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: Data
     */
    open class func compose(composeRequest: ComposeRequest, apiConfiguration: AllScreenshotsSDKAPIConfiguration = AllScreenshotsSDKAPIConfiguration.shared) async throws(ErrorResponse) -> Data {
        return try await composeWithRequestBuilder(composeRequest: composeRequest, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     - POST /v1/screenshots/compose
     - API Key:
       - type: apiKey X-API-Key (HEADER)
       - name: ApiKey
     - parameter composeRequest: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<Data> 
     */
    open class func composeWithRequestBuilder(composeRequest: ComposeRequest, apiConfiguration: AllScreenshotsSDKAPIConfiguration = AllScreenshotsSDKAPIConfiguration.shared) -> RequestBuilder<Data> {
        let localVariablePath = "/v1/screenshots/compose"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: composeRequest, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Data>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**

     - parameter jobId: (path)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: ComposeJobStatusResponse
     */
    open class func getComposeJobStatus(jobId: String, apiConfiguration: AllScreenshotsSDKAPIConfiguration = AllScreenshotsSDKAPIConfiguration.shared) async throws(ErrorResponse) -> ComposeJobStatusResponse {
        return try await getComposeJobStatusWithRequestBuilder(jobId: jobId, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     - GET /v1/screenshots/compose/jobs/{jobId}
     - API Key:
       - type: apiKey X-API-Key (HEADER)
       - name: ApiKey
     - parameter jobId: (path)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<ComposeJobStatusResponse> 
     */
    open class func getComposeJobStatusWithRequestBuilder(jobId: String, apiConfiguration: AllScreenshotsSDKAPIConfiguration = AllScreenshotsSDKAPIConfiguration.shared) -> RequestBuilder<ComposeJobStatusResponse> {
        var localVariablePath = "/v1/screenshots/compose/jobs/{jobId}"
        let jobIdPreEscape = "\(APIHelper.mapValueToPathItem(jobId))"
        let jobIdPostEscape = jobIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{jobId}", with: jobIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ComposeJobStatusResponse>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**

     - parameter layout: (query)  
     - parameter imageCount: (query)  
     - parameter canvasWidth: (query)  (optional, default to 1200)
     - parameter canvasHeight: (query)  (optional, default to 800)
     - parameter aspectRatios: (query)  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: LayoutPreviewResponse
     */
    open class func getLayoutPreview(layout: String, imageCount: Int, canvasWidth: Int? = nil, canvasHeight: Int? = nil, aspectRatios: [Double]? = nil, apiConfiguration: AllScreenshotsSDKAPIConfiguration = AllScreenshotsSDKAPIConfiguration.shared) async throws(ErrorResponse) -> LayoutPreviewResponse {
        return try await getLayoutPreviewWithRequestBuilder(layout: layout, imageCount: imageCount, canvasWidth: canvasWidth, canvasHeight: canvasHeight, aspectRatios: aspectRatios, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     - GET /v1/screenshots/compose/preview
     - API Key:
       - type: apiKey X-API-Key (HEADER)
       - name: ApiKey
     - parameter layout: (query)  
     - parameter imageCount: (query)  
     - parameter canvasWidth: (query)  (optional, default to 1200)
     - parameter canvasHeight: (query)  (optional, default to 800)
     - parameter aspectRatios: (query)  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<LayoutPreviewResponse> 
     */
    open class func getLayoutPreviewWithRequestBuilder(layout: String, imageCount: Int, canvasWidth: Int? = nil, canvasHeight: Int? = nil, aspectRatios: [Double]? = nil, apiConfiguration: AllScreenshotsSDKAPIConfiguration = AllScreenshotsSDKAPIConfiguration.shared) -> RequestBuilder<LayoutPreviewResponse> {
        let localVariablePath = "/v1/screenshots/compose/preview"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "layout": (wrappedValue: layout.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "image_count": (wrappedValue: imageCount.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "canvas_width": (wrappedValue: canvasWidth?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "canvas_height": (wrappedValue: canvasHeight?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "aspect_ratios": (wrappedValue: aspectRatios?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<LayoutPreviewResponse>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**

     - parameter apiConfiguration: The configuration for the http request.
     - returns: [ComposeJobSummaryResponse]
     */
    open class func listComposeJobs(apiConfiguration: AllScreenshotsSDKAPIConfiguration = AllScreenshotsSDKAPIConfiguration.shared) async throws(ErrorResponse) -> [ComposeJobSummaryResponse] {
        return try await listComposeJobsWithRequestBuilder(apiConfiguration: apiConfiguration).execute().body
    }

    /**
     - GET /v1/screenshots/compose/jobs
     - API Key:
       - type: apiKey X-API-Key (HEADER)
       - name: ApiKey
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<[ComposeJobSummaryResponse]> 
     */
    open class func listComposeJobsWithRequestBuilder(apiConfiguration: AllScreenshotsSDKAPIConfiguration = AllScreenshotsSDKAPIConfiguration.shared) -> RequestBuilder<[ComposeJobSummaryResponse]> {
        let localVariablePath = "/v1/screenshots/compose/jobs"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[ComposeJobSummaryResponse]>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }
}
