//
// CrawlAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

open class CrawlAPI {

    /**

     - parameter id: (path)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: CrawlResponse
     */
    open class func callGet(id: String, apiConfiguration: AllScreenshotsSDKAPIConfiguration = AllScreenshotsSDKAPIConfiguration.shared) async throws(ErrorResponse) -> CrawlResponse {
        return try await callGetWithRequestBuilder(id: id, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     - GET /v1/crawls/{id}
     - API Key:
       - type: apiKey X-API-Key (HEADER)
       - name: ApiKey
     - parameter id: (path)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<CrawlResponse> 
     */
    open class func callGetWithRequestBuilder(id: String, apiConfiguration: AllScreenshotsSDKAPIConfiguration = AllScreenshotsSDKAPIConfiguration.shared) -> RequestBuilder<CrawlResponse> {
        var localVariablePath = "/v1/crawls/{id}"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<CrawlResponse>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**

     - parameter id: (path)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: CrawlResponse
     */
    open class func cancel(id: String, apiConfiguration: AllScreenshotsSDKAPIConfiguration = AllScreenshotsSDKAPIConfiguration.shared) async throws(ErrorResponse) -> CrawlResponse {
        return try await cancelWithRequestBuilder(id: id, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     - POST /v1/crawls/{id}/cancel
     - API Key:
       - type: apiKey X-API-Key (HEADER)
       - name: ApiKey
     - parameter id: (path)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<CrawlResponse> 
     */
    open class func cancelWithRequestBuilder(id: String, apiConfiguration: AllScreenshotsSDKAPIConfiguration = AllScreenshotsSDKAPIConfiguration.shared) -> RequestBuilder<CrawlResponse> {
        var localVariablePath = "/v1/crawls/{id}/cancel"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<CrawlResponse>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**

     - parameter crawlRequest: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: CrawlCreatedResponse
     */
    open class func create(crawlRequest: CrawlRequest, apiConfiguration: AllScreenshotsSDKAPIConfiguration = AllScreenshotsSDKAPIConfiguration.shared) async throws(ErrorResponse) -> CrawlCreatedResponse {
        return try await createWithRequestBuilder(crawlRequest: crawlRequest, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     - POST /v1/crawls
     - API Key:
       - type: apiKey X-API-Key (HEADER)
       - name: ApiKey
     - parameter crawlRequest: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<CrawlCreatedResponse> 
     */
    open class func createWithRequestBuilder(crawlRequest: CrawlRequest, apiConfiguration: AllScreenshotsSDKAPIConfiguration = AllScreenshotsSDKAPIConfiguration.shared) -> RequestBuilder<CrawlCreatedResponse> {
        let localVariablePath = "/v1/crawls"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: crawlRequest, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<CrawlCreatedResponse>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**

     - parameter id: (path)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: Void
     */
    open class func delete(id: String, apiConfiguration: AllScreenshotsSDKAPIConfiguration = AllScreenshotsSDKAPIConfiguration.shared) async throws(ErrorResponse) {
        return try await deleteWithRequestBuilder(id: id, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     - DELETE /v1/crawls/{id}
     - API Key:
       - type: apiKey X-API-Key (HEADER)
       - name: ApiKey
     - parameter id: (path)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<Void> 
     */
    open class func deleteWithRequestBuilder(id: String, apiConfiguration: AllScreenshotsSDKAPIConfiguration = AllScreenshotsSDKAPIConfiguration.shared) -> RequestBuilder<Void> {
        var localVariablePath = "/v1/crawls/{id}"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = apiConfiguration.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "DELETE", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**

     - parameter page: (query)  (optional, default to 0)
     - parameter pageSize: (query)  (optional, default to 20)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: CrawlListResponse
     */
    open class func list(page: Int? = nil, pageSize: Int? = nil, apiConfiguration: AllScreenshotsSDKAPIConfiguration = AllScreenshotsSDKAPIConfiguration.shared) async throws(ErrorResponse) -> CrawlListResponse {
        return try await listWithRequestBuilder(page: page, pageSize: pageSize, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     - GET /v1/crawls
     - API Key:
       - type: apiKey X-API-Key (HEADER)
       - name: ApiKey
     - parameter page: (query)  (optional, default to 0)
     - parameter pageSize: (query)  (optional, default to 20)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<CrawlListResponse> 
     */
    open class func listWithRequestBuilder(page: Int? = nil, pageSize: Int? = nil, apiConfiguration: AllScreenshotsSDKAPIConfiguration = AllScreenshotsSDKAPIConfiguration.shared) -> RequestBuilder<CrawlListResponse> {
        let localVariablePath = "/v1/crawls"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "page": (wrappedValue: page?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "pageSize": (wrappedValue: pageSize?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<CrawlListResponse>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**

     - parameter id: (path)  
     - parameter pageId: (path)  
     - parameter output: (path)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: Data
     */
    open class func output(id: String, pageId: String, output: String, apiConfiguration: AllScreenshotsSDKAPIConfiguration = AllScreenshotsSDKAPIConfiguration.shared) async throws(ErrorResponse) -> Data {
        return try await outputWithRequestBuilder(id: id, pageId: pageId, output: output, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     - GET /v1/crawls/{id}/pages/{pageId}/outputs/{output}
     - API Key:
       - type: apiKey X-API-Key (HEADER)
       - name: ApiKey
     - parameter id: (path)  
     - parameter pageId: (path)  
     - parameter output: (path)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<Data> 
     */
    open class func outputWithRequestBuilder(id: String, pageId: String, output: String, apiConfiguration: AllScreenshotsSDKAPIConfiguration = AllScreenshotsSDKAPIConfiguration.shared) -> RequestBuilder<Data> {
        var localVariablePath = "/v1/crawls/{id}/pages/{pageId}/outputs/{output}"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let pageIdPreEscape = "\(APIHelper.mapValueToPathItem(pageId))"
        let pageIdPostEscape = pageIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{pageId}", with: pageIdPostEscape, options: .literal, range: nil)
        let outputPreEscape = "\(APIHelper.mapValueToPathItem(output))"
        let outputPostEscape = outputPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{output}", with: outputPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Data>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**

     - parameter id: (path)  
     - parameter page: (query)  (optional, default to 0)
     - parameter pageSize: (query)  (optional, default to 100)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: CrawlPagesResponse
     */
    open class func pages(id: String, page: Int? = nil, pageSize: Int? = nil, apiConfiguration: AllScreenshotsSDKAPIConfiguration = AllScreenshotsSDKAPIConfiguration.shared) async throws(ErrorResponse) -> CrawlPagesResponse {
        return try await pagesWithRequestBuilder(id: id, page: page, pageSize: pageSize, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     - GET /v1/crawls/{id}/pages
     - API Key:
       - type: apiKey X-API-Key (HEADER)
       - name: ApiKey
     - parameter id: (path)  
     - parameter page: (query)  (optional, default to 0)
     - parameter pageSize: (query)  (optional, default to 100)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<CrawlPagesResponse> 
     */
    open class func pagesWithRequestBuilder(id: String, page: Int? = nil, pageSize: Int? = nil, apiConfiguration: AllScreenshotsSDKAPIConfiguration = AllScreenshotsSDKAPIConfiguration.shared) -> RequestBuilder<CrawlPagesResponse> {
        var localVariablePath = "/v1/crawls/{id}/pages"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "page": (wrappedValue: page?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "pageSize": (wrappedValue: pageSize?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<CrawlPagesResponse>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }
}
