//
// JobAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

open class JobAPI {

    /**

     - parameter id: (path)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: JobResponse
     */
    open class func cancelJob(id: String, apiConfiguration: AllScreenshotsSDKAPIConfiguration = AllScreenshotsSDKAPIConfiguration.shared) async throws(ErrorResponse) -> JobResponse {
        return try await cancelJobWithRequestBuilder(id: id, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     - POST /v1/screenshots/jobs/{id}/cancel
     - API Key:
       - type: apiKey X-API-Key (HEADER)
       - name: ApiKey
     - parameter id: (path)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<JobResponse> 
     */
    open class func cancelJobWithRequestBuilder(id: String, apiConfiguration: AllScreenshotsSDKAPIConfiguration = AllScreenshotsSDKAPIConfiguration.shared) -> RequestBuilder<JobResponse> {
        var localVariablePath = "/v1/screenshots/jobs/{id}/cancel"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<JobResponse>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**

     - parameter screenshotRequest: (body)  
     - parameter idempotencyKey: (header) Unique submission key. Supported for responseType&#x3D;url; reuse with the same body to recover the original result. (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: AsyncJobCreatedResponse
     */
    open class func createAsyncJob(screenshotRequest: ScreenshotRequest, idempotencyKey: String? = nil, apiConfiguration: AllScreenshotsSDKAPIConfiguration = AllScreenshotsSDKAPIConfiguration.shared) async throws(ErrorResponse) -> AsyncJobCreatedResponse {
        return try await createAsyncJobWithRequestBuilder(screenshotRequest: screenshotRequest, idempotencyKey: idempotencyKey, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     - POST /v1/screenshots/async
     - API Key:
       - type: apiKey X-API-Key (HEADER)
       - name: ApiKey
     - parameter screenshotRequest: (body)  
     - parameter idempotencyKey: (header) Unique submission key. Supported for responseType&#x3D;url; reuse with the same body to recover the original result. (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<AsyncJobCreatedResponse> 
     */
    open class func createAsyncJobWithRequestBuilder(screenshotRequest: ScreenshotRequest, idempotencyKey: String? = nil, apiConfiguration: AllScreenshotsSDKAPIConfiguration = AllScreenshotsSDKAPIConfiguration.shared) -> RequestBuilder<AsyncJobCreatedResponse> {
        let localVariablePath = "/v1/screenshots/async"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: screenshotRequest, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
            "Idempotency-Key": idempotencyKey?.asParameter(codableHelper: apiConfiguration.codableHelper),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<AsyncJobCreatedResponse>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**

     - parameter id: (path)  
     - parameter outputId: (path)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: Data
     */
    open class func getJobOutputResult(id: String, outputId: String, apiConfiguration: AllScreenshotsSDKAPIConfiguration = AllScreenshotsSDKAPIConfiguration.shared) async throws(ErrorResponse) -> Data {
        return try await getJobOutputResultWithRequestBuilder(id: id, outputId: outputId, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     - GET /v1/screenshots/jobs/{id}/result/{outputId}
     - API Key:
       - type: apiKey X-API-Key (HEADER)
       - name: ApiKey
     - parameter id: (path)  
     - parameter outputId: (path)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<Data> 
     */
    open class func getJobOutputResultWithRequestBuilder(id: String, outputId: String, apiConfiguration: AllScreenshotsSDKAPIConfiguration = AllScreenshotsSDKAPIConfiguration.shared) -> RequestBuilder<Data> {
        var localVariablePath = "/v1/screenshots/jobs/{id}/result/{outputId}"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let outputIdPreEscape = "\(APIHelper.mapValueToPathItem(outputId))"
        let outputIdPostEscape = outputIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{outputId}", with: outputIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Data>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**

     - parameter id: (path)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: Data
     */
    open class func getJobResult(id: String, apiConfiguration: AllScreenshotsSDKAPIConfiguration = AllScreenshotsSDKAPIConfiguration.shared) async throws(ErrorResponse) -> Data {
        return try await getJobResultWithRequestBuilder(id: id, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     - GET /v1/screenshots/jobs/{id}/result
     - API Key:
       - type: apiKey X-API-Key (HEADER)
       - name: ApiKey
     - parameter id: (path)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<Data> 
     */
    open class func getJobResultWithRequestBuilder(id: String, apiConfiguration: AllScreenshotsSDKAPIConfiguration = AllScreenshotsSDKAPIConfiguration.shared) -> RequestBuilder<Data> {
        var localVariablePath = "/v1/screenshots/jobs/{id}/result"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Data>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**

     - parameter id: (path)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: JobResponse
     */
    open class func getJobStatus(id: String, apiConfiguration: AllScreenshotsSDKAPIConfiguration = AllScreenshotsSDKAPIConfiguration.shared) async throws(ErrorResponse) -> JobResponse {
        return try await getJobStatusWithRequestBuilder(id: id, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     - GET /v1/screenshots/jobs/{id}
     - API Key:
       - type: apiKey X-API-Key (HEADER)
       - name: ApiKey
     - parameter id: (path)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<JobResponse> 
     */
    open class func getJobStatusWithRequestBuilder(id: String, apiConfiguration: AllScreenshotsSDKAPIConfiguration = AllScreenshotsSDKAPIConfiguration.shared) -> RequestBuilder<JobResponse> {
        var localVariablePath = "/v1/screenshots/jobs/{id}"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<JobResponse>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**

     - parameter apiConfiguration: The configuration for the http request.
     - returns: [JobResponse]
     */
    open class func listJobs(apiConfiguration: AllScreenshotsSDKAPIConfiguration = AllScreenshotsSDKAPIConfiguration.shared) async throws(ErrorResponse) -> [JobResponse] {
        return try await listJobsWithRequestBuilder(apiConfiguration: apiConfiguration).execute().body
    }

    /**
     - GET /v1/screenshots/jobs
     - API Key:
       - type: apiKey X-API-Key (HEADER)
       - name: ApiKey
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<[JobResponse]> 
     */
    open class func listJobsWithRequestBuilder(apiConfiguration: AllScreenshotsSDKAPIConfiguration = AllScreenshotsSDKAPIConfiguration.shared) -> RequestBuilder<[JobResponse]> {
        let localVariablePath = "/v1/screenshots/jobs"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[JobResponse]>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }
}
