//
// ScheduleAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

open class ScheduleAPI {

    /**

     - parameter createScheduleRequest: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: ScheduleResponse
     */
    open class func createSchedule(createScheduleRequest: CreateScheduleRequest, apiConfiguration: AllScreenshotsSDKAPIConfiguration = AllScreenshotsSDKAPIConfiguration.shared) async throws(ErrorResponse) -> ScheduleResponse {
        return try await createScheduleWithRequestBuilder(createScheduleRequest: createScheduleRequest, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     - POST /v1/schedules
     - API Key:
       - type: apiKey X-API-Key (HEADER)
       - name: ApiKey
     - parameter createScheduleRequest: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<ScheduleResponse> 
     */
    open class func createScheduleWithRequestBuilder(createScheduleRequest: CreateScheduleRequest, apiConfiguration: AllScreenshotsSDKAPIConfiguration = AllScreenshotsSDKAPIConfiguration.shared) -> RequestBuilder<ScheduleResponse> {
        let localVariablePath = "/v1/schedules"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: createScheduleRequest, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ScheduleResponse>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**

     - parameter id: (path)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: Void
     */
    open class func deleteSchedule(id: String, apiConfiguration: AllScreenshotsSDKAPIConfiguration = AllScreenshotsSDKAPIConfiguration.shared) async throws(ErrorResponse) {
        return try await deleteScheduleWithRequestBuilder(id: id, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     - DELETE /v1/schedules/{id}
     - API Key:
       - type: apiKey X-API-Key (HEADER)
       - name: ApiKey
     - parameter id: (path)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<Void> 
     */
    open class func deleteScheduleWithRequestBuilder(id: String, apiConfiguration: AllScreenshotsSDKAPIConfiguration = AllScreenshotsSDKAPIConfiguration.shared) -> RequestBuilder<Void> {
        var localVariablePath = "/v1/schedules/{id}"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Void>.Type = apiConfiguration.requestBuilderFactory.getNonDecodableBuilder()

        return localVariableRequestBuilder.init(method: "DELETE", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**

     - parameter id: (path)  
     - parameter limit: (query)  (optional, default to 50)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: ScheduleHistoryResponse
     */
    open class func getExecutionHistory(id: String, limit: Int? = nil, apiConfiguration: AllScreenshotsSDKAPIConfiguration = AllScreenshotsSDKAPIConfiguration.shared) async throws(ErrorResponse) -> ScheduleHistoryResponse {
        return try await getExecutionHistoryWithRequestBuilder(id: id, limit: limit, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     - GET /v1/schedules/{id}/history
     - API Key:
       - type: apiKey X-API-Key (HEADER)
       - name: ApiKey
     - parameter id: (path)  
     - parameter limit: (query)  (optional, default to 50)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<ScheduleHistoryResponse> 
     */
    open class func getExecutionHistoryWithRequestBuilder(id: String, limit: Int? = nil, apiConfiguration: AllScreenshotsSDKAPIConfiguration = AllScreenshotsSDKAPIConfiguration.shared) -> RequestBuilder<ScheduleHistoryResponse> {
        var localVariablePath = "/v1/schedules/{id}/history"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "limit": (wrappedValue: limit?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ScheduleHistoryResponse>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**

     - parameter id: (path)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: ScheduleResponse
     */
    open class func getSchedule(id: String, apiConfiguration: AllScreenshotsSDKAPIConfiguration = AllScreenshotsSDKAPIConfiguration.shared) async throws(ErrorResponse) -> ScheduleResponse {
        return try await getScheduleWithRequestBuilder(id: id, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     - GET /v1/schedules/{id}
     - API Key:
       - type: apiKey X-API-Key (HEADER)
       - name: ApiKey
     - parameter id: (path)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<ScheduleResponse> 
     */
    open class func getScheduleWithRequestBuilder(id: String, apiConfiguration: AllScreenshotsSDKAPIConfiguration = AllScreenshotsSDKAPIConfiguration.shared) -> RequestBuilder<ScheduleResponse> {
        var localVariablePath = "/v1/schedules/{id}"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ScheduleResponse>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**

     - parameter apiConfiguration: The configuration for the http request.
     - returns: ScheduleListResponse
     */
    open class func listSchedules(apiConfiguration: AllScreenshotsSDKAPIConfiguration = AllScreenshotsSDKAPIConfiguration.shared) async throws(ErrorResponse) -> ScheduleListResponse {
        return try await listSchedulesWithRequestBuilder(apiConfiguration: apiConfiguration).execute().body
    }

    /**
     - GET /v1/schedules
     - API Key:
       - type: apiKey X-API-Key (HEADER)
       - name: ApiKey
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<ScheduleListResponse> 
     */
    open class func listSchedulesWithRequestBuilder(apiConfiguration: AllScreenshotsSDKAPIConfiguration = AllScreenshotsSDKAPIConfiguration.shared) -> RequestBuilder<ScheduleListResponse> {
        let localVariablePath = "/v1/schedules"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ScheduleListResponse>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**

     - parameter id: (path)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: ScheduleResponse
     */
    open class func pauseSchedule(id: String, apiConfiguration: AllScreenshotsSDKAPIConfiguration = AllScreenshotsSDKAPIConfiguration.shared) async throws(ErrorResponse) -> ScheduleResponse {
        return try await pauseScheduleWithRequestBuilder(id: id, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     - POST /v1/schedules/{id}/pause
     - API Key:
       - type: apiKey X-API-Key (HEADER)
       - name: ApiKey
     - parameter id: (path)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<ScheduleResponse> 
     */
    open class func pauseScheduleWithRequestBuilder(id: String, apiConfiguration: AllScreenshotsSDKAPIConfiguration = AllScreenshotsSDKAPIConfiguration.shared) -> RequestBuilder<ScheduleResponse> {
        var localVariablePath = "/v1/schedules/{id}/pause"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ScheduleResponse>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**

     - parameter id: (path)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: ScheduleResponse
     */
    open class func resumeSchedule(id: String, apiConfiguration: AllScreenshotsSDKAPIConfiguration = AllScreenshotsSDKAPIConfiguration.shared) async throws(ErrorResponse) -> ScheduleResponse {
        return try await resumeScheduleWithRequestBuilder(id: id, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     - POST /v1/schedules/{id}/resume
     - API Key:
       - type: apiKey X-API-Key (HEADER)
       - name: ApiKey
     - parameter id: (path)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<ScheduleResponse> 
     */
    open class func resumeScheduleWithRequestBuilder(id: String, apiConfiguration: AllScreenshotsSDKAPIConfiguration = AllScreenshotsSDKAPIConfiguration.shared) -> RequestBuilder<ScheduleResponse> {
        var localVariablePath = "/v1/schedules/{id}/resume"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ScheduleResponse>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**

     - parameter id: (path)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: ScheduleResponse
     */
    open class func triggerSchedule(id: String, apiConfiguration: AllScreenshotsSDKAPIConfiguration = AllScreenshotsSDKAPIConfiguration.shared) async throws(ErrorResponse) -> ScheduleResponse {
        return try await triggerScheduleWithRequestBuilder(id: id, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     - POST /v1/schedules/{id}/trigger
     - API Key:
       - type: apiKey X-API-Key (HEADER)
       - name: ApiKey
     - parameter id: (path)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<ScheduleResponse> 
     */
    open class func triggerScheduleWithRequestBuilder(id: String, apiConfiguration: AllScreenshotsSDKAPIConfiguration = AllScreenshotsSDKAPIConfiguration.shared) -> RequestBuilder<ScheduleResponse> {
        var localVariablePath = "/v1/schedules/{id}/trigger"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ScheduleResponse>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**

     - parameter id: (path)  
     - parameter updateScheduleRequest: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: ScheduleResponse
     */
    open class func updateSchedule(id: String, updateScheduleRequest: UpdateScheduleRequest, apiConfiguration: AllScreenshotsSDKAPIConfiguration = AllScreenshotsSDKAPIConfiguration.shared) async throws(ErrorResponse) -> ScheduleResponse {
        return try await updateScheduleWithRequestBuilder(id: id, updateScheduleRequest: updateScheduleRequest, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     - PUT /v1/schedules/{id}
     - API Key:
       - type: apiKey X-API-Key (HEADER)
       - name: ApiKey
     - parameter id: (path)  
     - parameter updateScheduleRequest: (body)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<ScheduleResponse> 
     */
    open class func updateScheduleWithRequestBuilder(id: String, updateScheduleRequest: UpdateScheduleRequest, apiConfiguration: AllScreenshotsSDKAPIConfiguration = AllScreenshotsSDKAPIConfiguration.shared) -> RequestBuilder<ScheduleResponse> {
        var localVariablePath = "/v1/schedules/{id}"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: updateScheduleRequest, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ScheduleResponse>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "PUT", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }
}
