//
// ScreenshotAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

open class ScreenshotAPI {

    /**

     - parameter screenshotRequest: (body)  
     - parameter idempotencyKey: (header) Unique submission key. Supported for responseType&#x3D;url; reuse with the same body to recover the original result. (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: Data
     */
    open class func captureSync(screenshotRequest: ScreenshotRequest, idempotencyKey: String? = nil, apiConfiguration: AllScreenshotsSDKAPIConfiguration = AllScreenshotsSDKAPIConfiguration.shared) async throws(ErrorResponse) -> Data {
        return try await captureSyncWithRequestBuilder(screenshotRequest: screenshotRequest, idempotencyKey: idempotencyKey, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     - POST /v1/screenshots
     - API Key:
       - type: apiKey X-API-Key (HEADER)
       - name: ApiKey
     - parameter screenshotRequest: (body)  
     - parameter idempotencyKey: (header) Unique submission key. Supported for responseType&#x3D;url; reuse with the same body to recover the original result. (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<Data> 
     */
    open class func captureSyncWithRequestBuilder(screenshotRequest: ScreenshotRequest, idempotencyKey: String? = nil, apiConfiguration: AllScreenshotsSDKAPIConfiguration = AllScreenshotsSDKAPIConfiguration.shared) -> RequestBuilder<Data> {
        let localVariablePath = "/v1/screenshots"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: screenshotRequest, codableHelper: apiConfiguration.codableHelper)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            "Content-Type": "application/json",
            "Idempotency-Key": idempotencyKey?.asParameter(codableHelper: apiConfiguration.codableHelper),
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Data>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**

     - parameter id: (path)  
     - parameter outputId: (path)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: Data
     */
    open class func getSyncCaptureOutputResult(id: String, outputId: String, apiConfiguration: AllScreenshotsSDKAPIConfiguration = AllScreenshotsSDKAPIConfiguration.shared) async throws(ErrorResponse) -> Data {
        return try await getSyncCaptureOutputResultWithRequestBuilder(id: id, outputId: outputId, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     - GET /v1/screenshots/captures/{id}/result/{outputId}
     - API Key:
       - type: apiKey X-API-Key (HEADER)
       - name: ApiKey
     - parameter id: (path)  
     - parameter outputId: (path)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<Data> 
     */
    open class func getSyncCaptureOutputResultWithRequestBuilder(id: String, outputId: String, apiConfiguration: AllScreenshotsSDKAPIConfiguration = AllScreenshotsSDKAPIConfiguration.shared) -> RequestBuilder<Data> {
        var localVariablePath = "/v1/screenshots/captures/{id}/result/{outputId}"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let outputIdPreEscape = "\(APIHelper.mapValueToPathItem(outputId))"
        let outputIdPostEscape = outputIdPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{outputId}", with: outputIdPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Data>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**

     - parameter id: (path)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: Data
     */
    open class func getSyncCaptureResult(id: String, apiConfiguration: AllScreenshotsSDKAPIConfiguration = AllScreenshotsSDKAPIConfiguration.shared) async throws(ErrorResponse) -> Data {
        return try await getSyncCaptureResultWithRequestBuilder(id: id, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     - GET /v1/screenshots/captures/{id}/result
     - API Key:
       - type: apiKey X-API-Key (HEADER)
       - name: ApiKey
     - parameter id: (path)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<Data> 
     */
    open class func getSyncCaptureResultWithRequestBuilder(id: String, apiConfiguration: AllScreenshotsSDKAPIConfiguration = AllScreenshotsSDKAPIConfiguration.shared) -> RequestBuilder<Data> {
        var localVariablePath = "/v1/screenshots/captures/{id}/result"
        let idPreEscape = "\(APIHelper.mapValueToPathItem(id))"
        let idPostEscape = idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{id}", with: idPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<Data>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**

     - parameter key: (path)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: JSONValue
     */
    open class func submissionStatus(key: String, apiConfiguration: AllScreenshotsSDKAPIConfiguration = AllScreenshotsSDKAPIConfiguration.shared) async throws(ErrorResponse) -> JSONValue {
        return try await submissionStatusWithRequestBuilder(key: key, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     - GET /v1/screenshots/submissions/{key}
     - API Key:
       - type: apiKey X-API-Key (HEADER)
       - name: ApiKey
     - parameter key: (path)  
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<JSONValue> 
     */
    open class func submissionStatusWithRequestBuilder(key: String, apiConfiguration: AllScreenshotsSDKAPIConfiguration = AllScreenshotsSDKAPIConfiguration.shared) -> RequestBuilder<JSONValue> {
        var localVariablePath = "/v1/screenshots/submissions/{key}"
        let keyPreEscape = "\(APIHelper.mapValueToPathItem(key))"
        let keyPostEscape = keyPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        localVariablePath = localVariablePath.replacingOccurrences(of: "{key}", with: keyPostEscape, options: .literal, range: nil)
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<JSONValue>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }
}
