//
// UsageAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

open class UsageAPI {

    /**

     - parameter days: (query)  (optional, default to 120)
     - parameter apiKeyIds: (query)  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: [DailyCaptureCountResponse]
     */
    open class func getActivity(days: Int? = nil, apiKeyIds: [String]? = nil, apiConfiguration: AllScreenshotsSDKAPIConfiguration = AllScreenshotsSDKAPIConfiguration.shared) async throws(ErrorResponse) -> [DailyCaptureCountResponse] {
        return try await getActivityWithRequestBuilder(days: days, apiKeyIds: apiKeyIds, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     - GET /v1/usage/activity
     - API Key:
       - type: apiKey X-API-Key (HEADER)
       - name: ApiKey
     - parameter days: (query)  (optional, default to 120)
     - parameter apiKeyIds: (query)  (optional)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<[DailyCaptureCountResponse]> 
     */
    open class func getActivityWithRequestBuilder(days: Int? = nil, apiKeyIds: [String]? = nil, apiConfiguration: AllScreenshotsSDKAPIConfiguration = AllScreenshotsSDKAPIConfiguration.shared) -> RequestBuilder<[DailyCaptureCountResponse]> {
        let localVariablePath = "/v1/usage/activity"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "days": (wrappedValue: days?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
            "apiKeyIds": (wrappedValue: apiKeyIds?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<[DailyCaptureCountResponse]>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**

     - parameter apiConfiguration: The configuration for the http request.
     - returns: QuotaStatusResponse
     */
    open class func getQuota(apiConfiguration: AllScreenshotsSDKAPIConfiguration = AllScreenshotsSDKAPIConfiguration.shared) async throws(ErrorResponse) -> QuotaStatusResponse {
        return try await getQuotaWithRequestBuilder(apiConfiguration: apiConfiguration).execute().body
    }

    /**
     - GET /v1/usage/quota
     - API Key:
       - type: apiKey X-API-Key (HEADER)
       - name: ApiKey
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<QuotaStatusResponse> 
     */
    open class func getQuotaWithRequestBuilder(apiConfiguration: AllScreenshotsSDKAPIConfiguration = AllScreenshotsSDKAPIConfiguration.shared) -> RequestBuilder<QuotaStatusResponse> {
        let localVariablePath = "/v1/usage/quota"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<QuotaStatusResponse>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**

     - parameter apiConfiguration: The configuration for the http request.
     - returns: UsageResponse
     */
    open class func getUsage(apiConfiguration: AllScreenshotsSDKAPIConfiguration = AllScreenshotsSDKAPIConfiguration.shared) async throws(ErrorResponse) -> UsageResponse {
        return try await getUsageWithRequestBuilder(apiConfiguration: apiConfiguration).execute().body
    }

    /**
     - GET /v1/usage
     - API Key:
       - type: apiKey X-API-Key (HEADER)
       - name: ApiKey
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<UsageResponse> 
     */
    open class func getUsageWithRequestBuilder(apiConfiguration: AllScreenshotsSDKAPIConfiguration = AllScreenshotsSDKAPIConfiguration.shared) -> RequestBuilder<UsageResponse> {
        let localVariablePath = "/v1/usage"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<UsageResponse>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }

    /**

     - parameter apiConfiguration: The configuration for the http request.
     - returns: ApiKeyUsageResponse
     */
    open class func getUsageByKey(apiConfiguration: AllScreenshotsSDKAPIConfiguration = AllScreenshotsSDKAPIConfiguration.shared) async throws(ErrorResponse) -> ApiKeyUsageResponse {
        return try await getUsageByKeyWithRequestBuilder(apiConfiguration: apiConfiguration).execute().body
    }

    /**
     - GET /v1/usage/keys
     - API Key:
       - type: apiKey X-API-Key (HEADER)
       - name: ApiKey
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<ApiKeyUsageResponse> 
     */
    open class func getUsageByKeyWithRequestBuilder(apiConfiguration: AllScreenshotsSDKAPIConfiguration = AllScreenshotsSDKAPIConfiguration.shared) -> RequestBuilder<ApiKeyUsageResponse> {
        let localVariablePath = "/v1/usage/keys"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<ApiKeyUsageResponse>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }
}
